### ISSUE TITLE
How about adding a feature getting online users

### ISSUE THREAD

**Issue by mr-cn** [fsgmhoward/shadowsocks-py-mu#16]
How to get the users who are online?
Someone says use a linux shell,to get the number of connections.
But a php shell may not have the permissions.
我去英语真难写
PS:这个程序支持自定义加密方式 这么牛逼，却好冷清……

**Comment by zuoruizhi** [comment]
看最后在线时间不就可以了吗

**Comment by mr-cn** [comment]
对哈。我怎么没想到
谢谢楼上
@zuoruizhi
