### ISSUE TITLE
error

### ISSUE THREAD

**Issue by angelsky11** [fsgmhoward/shadowsocks-py-mu#18]
你好，配合ss-panel 3.4.2一直是这种情况无法启动，请问怎么解决

Jul 25 01:34:58 INFO -----------------------------------------
Jul 25 01:34:58 INFO Multi-User Shadowsocks Server Starting...
Jul 25 01:34:58 INFO Current Server Version: 3.1.1
Jul 25 01:34:58 INFO Now using MultiUser API as the user interface
Jul 25 01:35:00 ERROR db thread except:No JSON object could be decoded
Jul 25 01:35:01 ERROR db thread except:No JSON object could be decoded

**Comment by zuoruizhi** [comment]
@angelsky11 用户的加密方式是什么

**Comment by fsgmhoward** [comment]
@angelsky11 请检查你的API地址是否正确。
应该会像`http://example.com/mu`这样子。

注意一下，假如你开了http跳转https的话，这个地址填写一定要是https，不然会导致POST时出现错误。
