### ISSUE TITLE
前端节点列表负载、在线人数等显示暂无数据呢？

### ISSUE THREAD

**Issue by Mr-XiaoGuan** [fsgmhoward/shadowsocks-py-mu#19]
第一台VPS安装SS-Panel V3 和 shadowsocks-py-mu ，一切显示正常
第二台VPS
第三台VPS
负载、在线人数、产生流量、uptime等等都是显示暂无数据。但是可以正常连接以及使用。
@fsgmhoward 
@zuoruizhi
@mengskysama

**Comment by zuoruizhi** [comment]
@Mr-XiaoGuan 第二台之后config.py中的NODE_ID 改了吗   ？

**Comment by zuoruizhi** [comment]
改成数据库中ss_node表中对应的id号

**Comment by zuoruizhi** [comment]
如果还找不到原因    打开SS_VERBOSE    发日志

**Comment by Mr-XiaoGuan** [comment]
NODE_ID = '3'  中ID号和数据表中一致，
API_ENABLED = False 如果写成True就会出错，唯一和第一台服务器不同的地方就是这个。

[root@Jm-VPN shadowsocks]# cat shadowsocks.log
Aug 18 17:19:11 INFO -----------------------------------------
Aug 18 17:19:11 INFO Multi-User Shadowsocks Server Starting...
Aug 18 17:19:11 INFO Current Server Version: 3.1.1-10-gf878e64

Aug 18 17:19:11 INFO Now using MySQL Database as the user interface
Aug 18 17:19:11 INFO Now starting manager thread...
Aug 18 17:19:16 INFO Now starting user pulling thread...
Aug 18 17:19:16 INFO db skipped port 80
Aug 18 17:19:16 INFO db downloaded
Aug 18 17:19:16 INFO Server Added:   P[10000], M[aes-256-cfb], E[78671100@qq.com]
Aug 18 17:19:16 INFO U[10000] Server Started with password [123123aA] and method [aes-256-cfb]
Aug 18 17:19:16 INFO Server Added:   P[10001], M[aes-256-cfb], E[mr.xiaoguan@gmail.com]
Aug 18 17:19:16 INFO U[10001] Server Started with password [123123aA] and method [aes-256-cfb]
Aug 18 17:19:21 INFO Now starting user pushing thread...
Aug 18 17:19:46 INFO db skipped port 80
Aug 18 17:19:46 INFO db downloaded

**Comment by fsgmhoward** [comment]
@zuoruizhi @Mr-XiaoGuan 这个是他自己的配置的问题。

现在这个服务端的逻辑是MySQL/API二选一，当API_ENABLE=True时完全不使用MySQL，估计是你API配置有问题（比如https漏打个s之类的）导致开启API的时候出现错误。**请根据配置文件里面的注释进行配置**

**只有在使用SSAPI的时候才会报告服务器负载和在线人数等参数，在使用数据库的时候只会报告用户使用的流量**
