### ISSUE TITLE
ERROR Except thrown while pulling user data:No JSON object could be decoded

### ISSUE THREAD

**Issue by xxsxx** [fsgmhoward/shadowsocks-py-mu#24]
填好api后 python servers.py 
显示
Aug 27 17:38:04 INFO Multi-User Shadowsocks Server Starting...
Aug 27 17:38:04 INFO Current Server Version: 3.1.1-12-g43249c6

Aug 27 17:38:04 INFO Now using MultiUser API as the user interface
Aug 27 17:38:04 INFO Now starting manager thread...
Aug 27 17:38:09 INFO Now starting user pulling thread...
Aug 27 17:38:09 ERROR Except thrown while pulling user data:No JSON object could be decoded

一脸懵逼。。
配置文件

```
# !!! Please rename config_example.py as config.py BEFORE editing it !!!

import logging
# !!! Only edit this line when you update your configuration file !!!
# After you update, the values of CONFIG_VERSION in config.py and
# config_example.py should be the same in order to start the server
CONFIG_VERSION = '20160623-2'


# Manyuser Interface Settings
# ---------------------------
# If API is enabled, database will be no longer used
# The known app that supports API is SS-Panel V3
# Be careful and check whether your app supports this API BEFORE you enable this feature
API_ENABLED = True  #False  #True

# Database Config
MYSQL_HOST = 'localhost'
MYSQL_PORT = 3306
MYSQL_USER = 'xx'
MYSQL_PASS = 'xx'
MYSQL_DB = 'xx'
# USUALLY this variable do not need to be changed
MYSQL_USER_TABLE = 'user'
# This is also the timeout of connecting to the API
MYSQL_TIMEOUT = 30

# Shadowsocks MultiUser API Settings
API_URL = 'http://ss.aiwo.cf/mu'
# API Key (you can find this in the .env file if you are using SS-Panel V3)
API_PASS = 'xx'
NODE_ID = '1'

# Time interval between 2 pulls from the database or API
CHECKTIME = 30
# Time interval between 2 pushes to the database or API
SYNCTIME = 120
# Choose True if youi want to use custom method and False if you don't
CUSTOM_METHOD = True


# Manager Settings
# ----------------
# USUALLY you can just keep this section unchanged
# It is not necessary to change the password if you only listen on 127.0.0.1
MANAGE_PASS = 'passwd'
# if you want manage in other server you should set this value to global ip
MANAGE_BIND_IP = '127.0.0.1'
# make sure this port is idle
MANAGE_PORT = 65000


# Network Settings
# ----------------
# Address binding settings
# if you want to bind ipv4 and ipv6 please use '::'
# if you want to bind only all of ipv4 please use '0.0.0.0'
# if you want to bind a specific IP you may use something like '4.4.4.4'
SS_BIND_IP = '::'
# This default method will be replaced by database record if applicable
SS_METHOD = 'aes-256-cfb'
# Choose whether enforce Shadowsocks One Time Auth (OTA)
# OTA will still be enabled for the client if it sends an AUTH Address type(0x10)
SS_OTA = False   #False #True
# Skip listening these ports
SS_SKIP_PORTS = [80]
# TCP Fastopen (Some OS may not support this, Eg.: Windows)
SS_FASTOPEN = False
# Shadowsocks Time Out
# It should > 180s as some protocol has keep-alive packet of 3 min, Eg.: bt
SS_TIMEOUT = 185


# Firewall Settings
# -----------------
# These settings are to prevent user from abusing your service
SS_FIREWALL_ENABLED = True
# Mode = whitelist or blacklist
SS_FIREWALL_MODE = 'blacklist'
# Member ports should be INTEGERS
# Only Ban these target ports (for blacklist mode)
SS_BAN_PORTS = [22, 23, 25]
# Only Allow these target ports (for whitelist mode)
SS_ALLOW_PORTS = [53, 80, 443, 8080, 8081]
# Trusted users (all target ports will be not be blocked for these users)
SS_FIREWALL_TRUSTED = [443]
# Banned Target IP List
SS_FORBIDDEN_IP = []


# Logging and Debugging Settings
# --------------------------
LOG_ENABLE = True
SS_VERBOSE = False
# Available Log Level: logging.NOTSET|DEBUG|INFO|WARNING|ERROR|CRITICAL
LOG_LEVEL = logging.INFO
LOG_FILE = 'shadowsocks.log'
# The following format is the one suggested for debugging
# LOG_FORMAT = '%(asctime)s %(filename)s[line:%(lineno)d] %(levelname)s %(message)s'
LOG_FORMAT = '%(asctime)s %(levelname)s %(message)s'
LOG_DATE_FORMAT = '%b %d %H:%M:%S'
```

**Comment by fsgmhoward** [comment]
= =发代码之前能先用三个反引号圈起来么....这被github当作MD处理了

我这从你的配置文件也看不出什么问题，貌似API配置是正确的

**Comment by xxsxx** [comment]
@fsgmhoward  试过了  
还是显示
> 
 Except thrown while pulling user data:No JSON object could be decoded 

 网页访问：域名/mu/users?key=<API

 KEY>  。
显示

> {"ret":1,"msg":"ok","data":[{"id":1,"email":"xxx@163.com","passwd":"xxx","t":1473273639,"u":0,"d":839852585,"transfer_enable":107517837312,"port":xxx,"switch":1,"enable":1,"type":1,"last_check_in_time":1472567900,"reg_date":"2016-09-08 02:40:39","invite_num":1,"expire_time":0,"method":"aes-256-cfb","custom_method":1,"custom_rss":1,"protocol":"auth_sha1_v2","protocol_param":"","obfs":"tls1.2_ticket_auth","obfs_param":""}]}

会不会是vps问题。。。

**Comment by zuoruizhi** [comment]
前端是dev版？

**Comment by xxsxx** [comment]
@fsgmhoward 是啊  用默认的也这样。。

**Comment by fsgmhoward** [comment]
看上去没有问题，返回的数据也是正确的JSON。你有设置什么防火墙防CC之类的东西么？

**Comment by xxsxx** [comment]
@fsgmhoward  木有。。默认开通8000到20000端口号。。。 用lnmp搭建的。。

**Comment by wonderful60** [comment]
遇到一样的问题，之前用着好好的，然后我把ss-panel迁移到另外一台服务器，然后在新ss-panel上面创建的账号一个都获取不到，包括管理员账号，但是通过访问http://xxx/mu/users?key=<APIKEY> 是能正常获取账号信息的，目前只能通过用数据库方式访问喽。

**Comment by wonderful60** [comment]
@xxsxx 我找到了我这边的原因了，是因为我对我的ss-panel在web服务器做了Ip访问限制导致了这个问题，将ip访问限制取消就好了😭
```
<Directory /opt/lampp/htdocs/ss-panel/public>
       AllowOverride All
       Order Deny,Allow
       Allow From all
       #Deny From all
       #Allow From 127.0.0.1
       #Allow From x.x.x.x
       #Allow From x.x.x.x
    </Directory>
```

**Comment by xxsxx** [comment]
@wonderful60  Deny From all 这个注释掉就可以了吗？  我试试。。

**Comment by fsgmhoward** [comment]
@xxsxx 可以通过这个方法检查是否是IP限制导致无法获取：
在SS服务器上执行`curl http://<Your Domain Name>/mu/users?key=<Your API Key>`

检查一下返回的信息是否是一个标准的JSON字符串。

**Comment by jipeng233** [comment]
@fsgmhoward 我遇到了相同的问题，curl 返回的信息是一个 json 字符串。

**Comment by JanydChang** [comment]
我用了百度的免费CDN，连接报错……取消了后就行了....垃圾百度

**Comment by panjian-win** [comment]
@wonderful60  大佬 请教一下 这个**<Directory /opt/lampp/htdocs/ss-panel/public>
       AllowOverride All
       Order Deny,Allow
       Allow From all
       #Deny From all
       #Allow From 127.0.0.1
       #Allow From x.x.x.x
       #Allow From x.x.x.x
    </Directory>**
在哪儿呢

**Comment by JanydChang** [comment]
由于您主站采用了CDN，导致服务端无法正常通过API接口与主站互通。去掉CDN即可解决！
我是这样弄好的...咸鱼一条,爬帖弄好的,啥也不懂,不知道能不能帮到你.

2017-06-28 13:33 GMT+08:00 panjian-win <notifications@github.com>:

**Comment by wonderful60** [comment]
@panjian-win 这是我这边用apache做web服务器的配置，里面设置了哪些ip可以访问这个web项目，如果curl没信息返回就查看一下是否web服务器设置的IP策略或者所在服务器是否设置了防火墙策略

**Comment by kilobps** [comment]
通过浏览器直接访问 http://xxx.com/mu/users?key=xxx  出现500 Internal Server Error错误，是什么原因？ 我看了日志，应该是在我重启该服务器之后，从200 OK 变成500 Internal Server Error错误的，是不是哪个进程没拉起来？多谢了。

**Comment by fsgmhoward** [comment]
@kilobps ss-panel的问题请去ss-panel的repo发issue问。
https://github.com/orvice/ss-panel
