### ISSUE TITLE
API 连接无法添加端口

### ISSUE THREAD

**Issue by yywudi** [fsgmhoward/shadowsocks-py-mu#25]
前端 ss-panel v3  github 最新代码
后端是这个shadowsocks-py-mu github 最新

前端经过了迁移，重新安装之后直接导入的shadowsocks数据库表，已经跑起来，也已经添加了节点，web访问一切正常。之前运行的节点还是正常使用。
重新开一个节点，配置好config.py 里的API相关参数之后启动 servers.py

现象：
节点能够连上前端，但是无法添加ss端口。 log如下，没有 server add 字段。netstat -nlp 查看也没有开启端口。

Oct 20 13:02:11 INFO Multi-User Shadowsocks Server Starting...
Oct 20 13:02:11 INFO Current Server Version: 3.1.1
Oct 20 13:02:11 INFO Now using MultiUser API as the user interface
Oct 20 13:02:11 INFO Now starting manager thread...
Oct 20 13:02:11 DEBUG using event model: epoll
Oct 20 13:02:16 INFO Now starting user pulling thread...
Oct 20 13:02:21 INFO Now starting user pushing thread...

但是通过 curl https://xxxx.com/mu/users?key=xxxxxxxxx&node=3 又能够获取前端传递过来的数据。包括用户/端口/密码等等

不知道是什么地方出错，针对API方式前后端通信，有什么debug方式么？

**Comment by yywudi** [comment]
经过各种加logging.info 
发现是manage.py 里handle_event函数收到的前端传过来的数据，"command" 参数始终是 'stat' 而不是'add'
很费解，前端是怎么决定传不传add的呢？我理解节点刚启动第一次和前端通信，应该传add，之后再传stat或者其他

**Comment by yywudi** [comment]
终于debug到问题所在了，通过curl https://xxxx.com/mu/users?key=xxxxxxxxx 获取到的JSON 文件里面，有个'switch'参数个type不知道为什么变成了unicode而不是int, 导致在del_server_out_of_bound_safe() 函数中判断 row[5] ==1 的时候出错。   

还需要进一步debug为啥前端传过来的这个参数变成了unicode类型，数据库里面都是int...

**Comment by kqkq** [comment]
感谢楼上提示错误原理，我已经解决了这个问题。

app/Models/Users.php

```
    protected $casts = [
        "t" => 'int',
        "u" => 'int',
        "d" => 'int',
        "port" => 'int',
        "switch" => 'int',     // Add this !!!
        "transfer_enable" => 'float',
        "enable" => 'int',
        'is_admin' => 'boolean',
    ];
```

**Comment by yywudi** [comment]
是的，我也是这么解决的。
不过后来我稍微看了下代码，'enable' 参数是可以通过网页设置修改的，这个比较明显。不过没搞明白这个'switch'参数有什么作用，没找到前端会在什么地方修改这个值来影响后端。

**Comment by kqkq** [comment]
嗯，我也没搞懂switch是干嘛的。。

**Comment by zuoruizhi** [comment]
前端switch无用，后端和enable一样
