### ISSUE TITLE
请问数据库里u (upload transfer)一直为0怎么办

### ISSUE THREAD

**Issue by n2ray** [fsgmhoward/shadowsocks-py-mu#29]
前端 ss-panel v3 github 最新代码
后端是这个shadowsocks-py-mu github 最新

所有运行正常，除了用户数据表里u (upload transfer)一直为0，请问是什么地方出问题了？

**Comment by zuoruizhi** [comment]
正常，上传下载流量全部统计在d中

**Comment by n2ray** [comment]
了解，非常感谢

**Comment by freeyoung** [comment]
我其实一直不明白为什么这么设计，原先明明是分开统计的

**Comment by fsgmhoward** [comment]
@freeyoung 其实我不清楚这样合并的原因，我当初fork的是mengskysama/shadowsocks-rm这个repo，在fork的时候已经是合并统计了。

mengskysama/shadowsocks这个repo是从原本shadowsocks/shadowsocks fork过来的，u和d是分开统计的。

不过我没看过这两个repo（mengskysama/shadowsocks和mengskysama/shadowsocks-rm）之间相差的commit。改天有空去研究一下看看这样改的缘由。

**Comment by logtee** [comment]
上传和下载还是分开的好,希望能改回去呢~
