### ISSUE TITLE
运行 python servers.py 时出错

### ISSUE THREAD

**Issue by pbwind** [fsgmhoward/shadowsocks-py-mu#31]
你好。
系统为CentOS 6 X64
前端 esdeathlove/ss-panel-v3-mod
后端 fsgmhoward/shadowsocks-py-mu
执行python servers.py  出错。
错误提示为： ERROR Except thrown while pushing user data:'data'.
相应的 esdeathlove/ss-panel-v3-mod 里面设置.config.php
muKey = 

config.py 里面仅设置  
API_ENABLED = True 
API_URL =
API_PASS =

**Comment by fsgmhoward** [comment]
你提供的这些信息我也没法帮你判断原因啊......

**Comment by pbwind** [comment]
Feb 19 14:58:16 INFO -----------------------------------------
Feb 19 14:58:16 INFO Multi-User Shadowsocks Server Starting...
Feb 19 14:58:16 INFO Current Server Version: 3.1.1-22-g1ba3d8b

Feb 19 14:58:16 INFO Now using MultiUser API as the user interface
Feb 19 14:58:16 INFO Now starting manager thread...
Feb 19 14:58:21 INFO Now starting user pulling thread...
Traceback (most recent call last):
  File "/root/shadowsocks-py-mu/shadowsocks/dbtransfer.py", line 228, in thread_db
    rows = DbTransfer.pull_db_all_user()
  File "/root/shadowsocks-py-mu/shadowsocks/dbtransfer.py", line 255, in pull_db_all_user
    rows = DbTransfer.pull_api_user()
  File "/root/shadowsocks-py-mu/shadowsocks/dbtransfer.py", line 292, in pull_api_user
    for user in data['data']:
KeyError: 'data'
Feb 19 14:58:22 ERROR Except thrown while pulling user data:'data'
Feb 19 14:58:26 INFO Now starting user pushing thread...
Feb 19 14:58:26 INFO api upload: pushing transfer statistics
Traceback (most recent call last):
  File "/root/shadowsocks-py-mu/shadowsocks/dbtransfer.py", line 243, in thread_push
    DbTransfer.get_instance().push_db_all_user()
  File "/root/shadowsocks-py-mu/shadowsocks/dbtransfer.py", line 84, in push_db_all_user
    users = DbTransfer.pull_api_user()
  File "/root/shadowsocks-py-mu/shadowsocks/dbtransfer.py", line 292, in pull_api_user
    for user in data['data']:
KeyError: 'data'
Feb 19 14:58:26 ERROR Except thrown while pushing user data:'data'
Traceback (most recent call last):
  File "/root/shadowsocks-py-mu/shadowsocks/dbtransfer.py", line 228, in thread_db
    rows = DbTransfer.pull_db_all_user()
  File "/root/shadowsocks-py-mu/shadowsocks/dbtransfer.py", line 255, in pull_db_all_user
    rows = DbTransfer.pull_api_user()
  File "/root/shadowsocks-py-mu/shadowsocks/dbtransfer.py", line 292, in pull_api_user
    for user in data['data']:
KeyError: 'data'
Feb 19 14:58:53 ERROR Except thrown while pulling user data:'data'
Traceback (most recent call last):
  File "/root/shadowsocks-py-mu/shadowsocks/dbtransfer.py", line 228, in thread_db
    rows = DbTransfer.pull_db_all_user()
  File "/root/shadowsocks-py-mu/shadowsocks/dbtransfer.py", line 255, in pull_db_all_user
    rows = DbTransfer.pull_api_user()
  File "/root/shadowsocks-py-mu/shadowsocks/dbtransfer.py", line 292, in pull_api_user
    for user in data['data']:
KeyError: 'data'
Feb 19 14:59:23 ERROR Except thrown while pulling user data:'data'

**Comment by pbwind** [comment]
2月19日14:58:16 INFO -----------------------------------------
2月19 14:58:16 INFO多用户Shadowsocks服务器开始...
Feb 19 14:58:16 INFO当前服务器版本：3.1.1-22-g1ba3d8b

2月19日14:58:16 INFO现在使用MultiUser API作为用户界面
Feb 19 14:58:16 INFO现在开始管理器线程...
Feb 19 14:58:21 INFO现在开始用户拉线程...
Traceback最近调用最后）：
文件“/root/shadowsocks-py-mu/shadowsocks/dbtransfer.py”，第228
行，在thread_db rows = DbTransfer.pull_db_all_user（）
文件“/ root / shadowsocks-py-mu / shadowsocks / dbtransfer。
py“，行255，在pull_db_all_user
rows = DbTransfer.pull_api_user（）
文件”/root/shadowsocks-py-mu/shadowsocks/dbtransfer.py“，第292行，在pull_api_user中
用于data ['data']中的用户：
KeyError： '
data'Feb 19 14:58:22 ERROR在拉取用户数据时抛出异常：'
data'Feb 19 14:58:26 INFO现在开始用户推送线程...
Feb 19 14:58:26 INFO api upload：pushing transfer统计
Traceback（最近最后调用）：
文件“/root/shadowsocks-py-mu/shadowsocks/dbtransfer.py”，第243行，在thread_push
DbTransfer.get_instance（）。push_db_all_user（）
文件“/ root / shadowsocks-亩/ 2.6.8 / dbtransfer.py“，行84，在push_db_all_user
用户= DbTransfer.pull_api_user（）
文件”/root/shadowsocks-py-mu/shadowsocks/dbtransfer.py“，第292行，在pull_api_user
用户数据[”数据']：
KeyError：'
data'Feb 19 14:58:26 ERROR除非在推送用户数据时抛出：'
data'Traceback（最近调用最后）：
文件“/ root / shadowsocks-py-mu / shadowsocks / dbtransfer。 python_user_user rows
=“DbTransfer.pull_api_user（） File”/ root / inline_db
rows = DbTransfer.pull_db_all_user（）
文件“/root/shadowsocks-py-mu/shadowsocks/dbtransfer.py”，第255
行，
pull_api_user中
的用户数据['data']中的行：shadowsocks-py-mu / shadowsocks / dbtransfer.py“ ：
KeyError：'
data'Feb 19 14:58:53 ERROR在拉取用户数据时抛出异常：'data '
traceback（最近最后调用）：
文件“/root/shadowsocks-py-mu/shadowsocks/dbtransfer.py”，第228
行，在thread_db rows = DbTransfer.pull_db_all_user（）
文件“/ root / shadowsocks-py-mu / pull_api_user 中 的用户的数据['data'
]中的行“/root/shadowsocks-py-mu/shadowsocks/dbtransfer.py”，第292
行中的第一行“shadowsocks / dbtransfer.py”，第255 行中的row_db_all_user rows =
DbTransfer.pull_api_user ]： KeyError：' data'Feb 19 14:59:23
ERROR在拉取用户数据时抛出异常：'data'



这种是因为dbtransfer.py这个文件要设置吗？
请帮忙看一下。
或者还需要什么信息？请告诉我，我会提供相关信息给你。

谢谢

2017-02-19 14:50 GMT+08:00 Howard Liu <notifications@github.com>:

**Comment by fsgmhoward** [comment]
@phwind 不需要，你唯一需要改的只是config.py。

如果你确认你的API地址没填错（看我上一条回复），那只能是你的面板不兼容的原因。

**Comment by pbwind** [comment]
我有改config py。
AIP确认没错。 我都是在本地改好以后，在上传到服务器的。

面板不兼容，还是说我不用API，可以使用别的方法，比如直接设置服务器地址吗？

VPS 为搬瓦工。

谢谢

**Comment by fsgmhoward** [comment]
Er...如果是API不兼容的话（你那个面板是ss-panel fork过来按道理来说应该是兼容的），你可以直接用数据库。如何配置请看README.md

还有就是，你说没有改config.py，是指config.py里面你的配置留空了么

**Comment by pbwind** [comment]
前端面板是SS-PANEL V3魔改版。
也是在那边看教程的。 他那边建议的 是使用SSR。 不想用。
所以就配合shadowsocks-py-mu 一起使用。

明天配置一下数据库看看。

**Comment by zyd2001** [comment]
好像魔改版的api不太一样，SSR教程里config设置api版本就要写成sspanelv3-mod

**Comment by iyuco** [comment]
遇到了同样的问题，面板为什么会不兼容呢

**Comment by qingyede** [comment]
esdeathlove/ss-panel-v3-mod 已经不兼容这个版本的了，建议直接用原版的panel，没有问题
