### ISSUE TITLE
嗯,我发现了一个bug, if row[5] == 1 and row[6] == 1 and row[1] + row[2] < row[3]: dbtransfer.py line:214

### ISSUE THREAD

**Issue by CicadaBear** [fsgmhoward/shadowsocks-py-mu#34]
我所用的ss-panel,shadowsocks-py-mu都是目前最新版本，发现了一个问题，添加不了用户（也就是想要的端口没有按预期打开）,理论上python servers.py 之后我应该等着看到Add[Server][Port]就对了，但是没有出现。调试了后发现 sendAddCommand没有执行，dbtransfer.py line:214，if row[5] == 1 and row[6] == 1 and row[1] + row[2] < row[3]永远是False。之后发现row[5]== u'1'，是字符串“1”。row[5]，Api返回的switch的值，我不知道这个问题是ss-panel改出来的问题，还是shadowsocks-py-mu的问题，应该属于服务端，希望后边的朋友可以看到避免。
http://ss.cicadabear.cc/mu/users?key=password&node=1
Api返回数据
```
{
  "ret": 1,
  "msg": "ok",
  "data": [
    {
      "id": 1,
      "email": "jack@cicadabear.cc",
      "passwd": "password",
      "t": 0,
      "u": 0,
      "d": 0,
      "transfer_enable": 5469372416,
      "port": 1025,
      "protocol": "origin",
      "obfs": "plain",
      "switch": "1",
      "enable": 1,
      "type": "1",
      "last_check_in_time": "1488452346",
      "reg_date": "2017-03-02 05:56:34",
      "invite_num": "0",
      "expire_time": "0",
      "method": "aes-256-cfb"
    }
  ]
}
```

**Comment by fsgmhoward** [comment]
之前好像也有人提过这个问题，忘记有没有人解答了。我自己的站点没出现这个问题（不过我用的ss-panel是比较旧的版本）。

我重新查了一下SS-Panel的源文件，`db.sql`中定义user表switch与type字段都是Tinyint(4)类型，然后`UserController.php`中是直接User::all()然后echoJson。我真没想明白是哪里会把1变成"1"输出

**Comment by CicadaBear** [comment]
找了半天终于找着问题了，以前从没碰到过，我在本地把ss-panel跑了一遍，本地好好的。我在我的Ubuntu上也跑了一下，Ubuntu上的问题跟vps的CentOS一样。Ubuntu的用的跟我本地用的同一个数据库，所以不是数据库造成的，我也不懂slim框架，之后看到UserModel里有类似于转化类型的代码。
```
class User extends Model

{
    protected $table = "user";

    public $isLogin;

    public $isAdmin;

    protected $casts = [
        "t" => 'int',
        "u" => 'int',
        "d" => 'int',
        "port" => 'int',
        "transfer_enable" => 'float',
        "enable" => 'int',
        'is_admin' => 'boolean',
    ];
```
好像作者知道这个问题，所以做了转换，但是switch给忘了，虽然enable跟swith,type都是tinyint但是enable没事就在这，搜了一下[mysql-integer-field-is-returned-as-string-in-php](http://stackoverflow.com/questions/5323146/mysql-integer-field-is-returned-as-string-in-php)，原来是php-mysql的驱动就会造成把int视作string,换成php-mysqlnd驱动,就没事。

**Comment by yywudi** [comment]
https://github.com/fsgmhoward/shadowsocks-py-mu/issues/25

**Comment by fsgmhoward** [comment]
原来如此。
不过mysqlnd在PHP5.4+就已经默认被编译。我记得Ubuntu 14.04的repo也更新PHP到5.6+了吧，怎么还会有这个问题？
建议你给ss-panel那个repo也发一个issue让orvice修复一下这个问题。我这边也找个时间修复一下，多谢反馈。

**Comment by CicadaBear** [comment]
好的
