### ISSUE TITLE
关于设备连接数和端口限速

### ISSUE THREAD

**Issue by n2ray** [fsgmhoward/shadowsocks-py-mu#35]
你的版本配合sspanle是最好用的，所以想问问是否能加入shadowsocksr的新的设备连接数和端口限速设置？
"protocol_param"
"speed_limit_per_con"
"speed_limit_per_user"

**Comment by haoerloveyou** [comment]
支持楼上，愿意一起努力。php不熟悉，iOS 开发着 希望能在客户端上献上一份力，fork一份源代码 准备改改支持iOS9~10

**Comment by mzfqy** [comment]
啥时候加这个功能呢

**Comment by fsgmhoward** [comment]
关于`protocol_param`，这个参数是SSR特有的，原版SS（及其兼容派生，比如本repo）没有`protocol`这种东西。至于限速功能，有待研究。

不过本repo使用的MU-API协议并没有获取这些参数的实现。本repo的API（包括数据库接口）协议对应的是`ss-panel v3`的[MU V2](https://github.com/orvice/ss-panel/wiki/Mu-V2)。

**Comment by jayruen** [comment]
@fsgmhoward 可否提供下实现全局端口限速第三方实现方案？

**Comment by fsgmhoward** [comment]
@jayruen 你可以尝试iptables+tc。虽然我认为应该不只有这种方案，但其余的我都没怎么了解过。具体实现方案请务必善用搜索引擎。
