### ISSUE TITLE
发现一个能使服务崩溃的问题

### ISSUE THREAD

**Issue by qingyede** [fsgmhoward/shadowsocks-py-mu#36]
先贴日志

Mar 06 12:31:11 INFO U[8896] TCP CONN: RP[28064] A[::ffff:108.61-->꨻
]󮔶nǏշ~=?S>ս񺣡i>8ҵiч%Š
��g-wZU]d꧔ç
UʏҋqݷߣبʂkkǛ`ߏlW昵܇fɒƁ̝Ӱ񖛘,6ܻѧ׸ЂB3󔲔41PgtՠJ󝮇@ظ{힠gǩۓù
0z§!Ў4ŞȚձdĔvHMm⾆WبOCIڮ+��Ń]
Mar 06 12:31:11 WARNING U[8896] One time auth fail
Mar 06 12:31:57 WARNING send_command exception: timed out

这个日志在-->后面是乱码，我搜索TCP CONN 找到了源码在tcprelay.py 的338行记录的

if firewall_blocked:
                logging.warning('U[%d] TCP PORT BANNED: RP[%d] A[%s-->%s]' % (
                    self._config['server_port'], remote_port,
                    addr, common.to_str(remote_addr)
                ))
                return
            else:
                logging.info('U[%d] TCP CONN: RP[%d] A[%s-->%s]' % (
                    self._config['server_port'], remote_port,
                    addr, common.to_str(remote_addr)
                ))

应该是remote_addr 字符有问题，但是不明白？

此问题已经导致服务多次挂掉

**Comment by fsgmhoward** [comment]
乱码是因为有人往你服务器8896端口发了一个无效的数据包（比如直接HTTP访问之类的）但是又正好符合封包标准就会这样。

这个问题我自己也碰到过，但是没碰到过服务端直接炸掉。

有空研究我一下。

**Comment by zuoruizhi** [comment]
出现乱码之后其他的端口还能否使用？

**Comment by zuoruizhi** [comment]
建议可以先彻底关闭OTA试下

首先配置文件关闭OTA开关
然后参照后面图片修改代码

配置文件的开关控制的是强制OTA，默认情况，同时支持OTA和非OTA，根据数据包判断
![1](https://cloud.githubusercontent.com/assets/8614920/23614695/d745b8a8-02be-11e7-8b7c-0c95810d28cc.png)
![2](https://cloud.githubusercontent.com/assets/8614920/23614698/d98a0f38-02be-11e7-80f4-f78fee9de21a.png)

**Comment by qingyede** [comment]
出现乱码后所有端口都不能用了。我只能重启ss。
然后发生乱码之前ota在配置中是关闭的。我今天先强制关闭ota测试几天看

**Comment by qingyede** [comment]
请问我能否针对这种链接直接忽略掉ta。丢弃掉。我今天有空读下源码。以前都是直接用不想去学。

**Comment by qingyede** [comment]
刚刚我又查看了前几天的日志，发现乱码的时候端口很高，RP[28064]，RP[56161] ，这个好像不正常，会不会是BT

**Comment by fsgmhoward** [comment]
不一定的，因为这个端口号是从封包中解析出来的。地址有问题说明这个数据包是有问题的，所以RP不一定是真正访问的端口。
如果是BT，Remote_addr可以显示目标主机的IP地址而不是乱码。
你的用户是不是用了ssr+混淆来访问你的SS节点了？建议问一下你这个用户的本地环境（如果每次都是端口号8896这个用户的问题的话）

**Comment by qingyede** [comment]
谢谢，我先把ota关闭，然后把高端口也封闭了不让访问，先使用一段时间再说。

**Comment by qingyede** [comment]
看了日志，发现不是一个端口，还有另外一个也是一样，并且乱码的前一个日志记录是btmeet.org，是一个磁力网站
我服务器ip我删减了

Mar 06 00:20:20 INFO U[8897] TCP CONN: RP[80] A[::ffff:108.61.1-->104.27.153.97]
Mar 06 00:20:20 INFO U[8897] TCP CONN: RP[80] A[::ffff:108.61.1-->www.btmeet.org]
Mar 06 00:20:20 INFO U[8897] TCP CONN: RP[56161] A[::ffff:108.61-->'ס7VЛZu	ݙԂeْb-ڊک9꾳3[τ놉IҲWӃ?۰ݠeb	񈿼dήE򔵅Ґ(Ⱥ^��Q��ގͷP
ѵAA|؇FU��S��̷��2) ۫Rׄ٦]
Mar 06 00:20:20 WARNING U[8897] One time auth fail
Mar 06 00:20:29 INFO api downloaded
Mar 06 00:20:30 WARNING send_command exception: timed out

**Comment by qingyede** [comment]
经过多天的调整，现在发现是下面的情况会停止服务




日志如下
Mar 13 12:35:36 dbtransfer.py[line:58] WARNING send_command exception: timed out
Mar 13 12:35:36 dbtransfer.py[line:234] ERROR pull thread except:No JSON object could be decoded
Mar 13 12:45:37 dbtransfer.py[line:58] WARNING send_command exception: timed out
Mar 13 12:45:37 dbtransfer.py[line:234] ERROR pull thread except:No JSON object could be decoded
Mar 13 12:54:02 dbtransfer.py[line:248] ERROR push thread except:timed out
Mar 13 12:55:39 dbtransfer.py[line:58] WARNING send_command exception: timed out
Mar 13 12:55:39 dbtransfer.py[line:234] ERROR pull thread except:No JSON object could be decoded
Mar 13 13:05:40 dbtransfer.py[line:58] WARNING send_command exception: timed out
Mar 13 13:05:40 dbtransfer.py[line:234] ERROR pull thread except:No JSON object could be decoded
Mar 13 13:15:42 dbtransfer.py[line:58] WARNING send_command exception: timed out
Mar 13 13:15:42 dbtransfer.py[line:234] ERROR pull thread except:No JSON object could be decoded
Mar 13 13:24:04 dbtransfer.py[line:248] ERROR push thread except:timed out
Mar 13 13:25:43 dbtransfer.py[line:58] WARNING send_command exception: timed out
Mar 13 13:25:43 dbtransfer.py[line:234] ERROR pull thread except:No JSON object could be decoded
Mar 13 13:35:44 dbtransfer.py[line:58] WARNING send_command exception: timed out
Mar 13 13:35:44 dbtransfer.py[line:234] ERROR pull thread except:No JSON object could be decoded

代码中这里，line58是异常捕获的日志

@staticmethod
    def send_command(cmd):
        data = ''
        try:
            cli = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
            cli.settimeout(1)
            cli.sendto(cmd, ('%s' % config.MANAGE_BIND_IP, config.MANAGE_PORT))
            data, addr = cli.recvfrom(1500)
            cli.close()
            # TODO: bad way solve timed out
            time.sleep(0.05)
        except Exception as e:
            if config.SS_VERBOSE:
                import traceback
                traceback.print_exc()
            logging.warn('send_command exception: %s' % e)
        return data

**Comment by fsgmhoward** [comment]
麻烦把`config.py`里面的`SS_VERBOSE`调成`True`，然后把整个Trace发上来。

你确定不是你面板或者数据库宕了？

**Comment by qingyede** [comment]
开始我也怀疑是sspanel的问题，但是ss我开了三个点，另外2个点从来就没有出现过问题。我早上详细看了日志的行号，是pull user 之后send_command 的异常，然后我发现在这个之前tcprelay.py的服务已经很久没有日志了，tcp服务可能挂了。

挂掉的ss服务在vultr上，正常运行的在lin上，

Mar 13 12:20:15 tcprelay.py[line:342] INFO U[8868] TCP CONN: RP[443] A[::ffff:108.61. -->safebrowsing.googleapis.com]
Mar 13 12:23:29 dbtransfer.py[line:58] WARNING send_command exception: timed out
Mar 13 12:23:29 dbtransfer.py[line:234] ERROR pull thread except:No JSON object could be decoded
Mar 13 12:33:32 dbtransfer.py[line:58] WARNING send_command exception: timed out
Mar 13 12:33:32 dbtransfer.py[line:234] ERROR pull thread except:No JSON object could be decoded
Mar 13 12:43:34 dbtransfer.py[line:58] WARNING send_command exception: timed out
Mar 13 12:43:34 dbtransfer.py[line:234] ERROR pull thread except:No JSON object could be decoded
Mar 13 12:52:15 dbtransfer.py[line:248] ERROR push thread except:timed out
Mar 13 12:53:36 dbtransfer.py[line:58] WARNING send_command exception: timed out
Mar 13 12:53:36 dbtransfer.py[line:234] ERROR pull thread except:No JSON object could be decoded
