### ISSUE TITLE
请问有没有最大用户数限制？

### ISSUE THREAD

**Issue by citaret** [fsgmhoward/shadowsocks-py-mu#37]
如果数据库中一个用户对应一个端口的话，那用户数是不是不能超过端口数了？

**Comment by zuoruizhi** [comment]
一个IP最多有65535个端口，足够用的，全用光了还可以加IP

**Comment by fsgmhoward** [comment]
如果你真的有好几万用户，你也不指望你一台机器能拖得动吧....理论上你能把非必要的端口全用于SS服务器。

**Comment by citaret** [comment]
谢谢，明白了。
