### ISSUE TITLE
servers.py运行出现401错误提示

### ISSUE THREAD

**Issue by mooyxu** [fsgmhoward/shadowsocks-py-mu#38]
Apr 01 15:54:42 INFO Multi-User Shadowsocks Server Starting...
Apr 01 15:54:42 INFO Current Server Version: 3.1.1-23-g3a4adfd

Apr 01 15:54:42 INFO Now using MultiUser API as the user interface
Apr 01 15:54:42 INFO Now starting manager thread...
Apr 01 15:54:48 INFO Now starting user pulling thread...
Apr 01 15:54:48 ERROR Except thrown while pulling user data:('http error', 401, 'Unauthorized', <httplib.HTTPMessage instance at 0x7f9f54abe200>)
Apr 01 15:54:57 INFO Now starting user pushing thread...
Apr 01 15:54:57 ERROR Except thrown while pushing user data:('http error', 401, 'Unauthorized', <httplib.HTTPMessage instance at 0x7f9f54ad1290>)

**Comment by zuoruizhi** [comment]
Api配置错误

**Comment by mooyxu** [comment]
# Shadowsocks MultiUser API Settings
API_URL = 'http://ss.xxxxxx.com/mu'
# API Key (you can find this in the .env file if you are using SS-Panel V3)
API_PASS = 'xxxxxxxxxx'
NODE_ID = '1'

api和pass部分好像没错吧？我用的ss-panel v3前端。

**Comment by mooyxu** [comment]
> # Shadowsocks MultiUser API Settings
API_URL = 'http://ss.xxxxxxxxx.com/mu'
# API Key (you can find this in the .env file if you are using SS-Panel V3)
API_PASS = 'xxxxxxxx'
NODE_ID = '1'

这是我api和passwd部分的配置。
用的是ss-panel-v3。
ss.xxxxxxxxx.com指向的是ss-panel/public，做了open_basedir。

这里有错？

**Comment by mooyxu** [comment]
```
# Shadowsocks MultiUser API Settings
API_URL = 'http://ss.xxxxxxxxx.com/mu'
# API Key (you can find this in the .env file if you are using SS-Panel V3)
API_PASS = 'xxxxxxxxxxx'
NODE_ID = '1'
```

这是我api和passwd部分的配置。
用的是ss-panel-v3。
ss.xxxxxxxxx.com指向的是ss-panel/public，做了open_basedir。

这里有错？

**Comment by zuoruizhi** [comment]
前端配置文件呢

**Comment by zuoruizhi** [comment]
https://github.com/mengskysama/shadowsocks-rm/wiki/关于mu-API-V1版本配置说明

**Comment by fsgmhoward** [comment]
检查API PASS是否正确、是否用了CDN（某些CDN有可能拦截了SS服务端的请求）。
如果用了CDN请把`http://ss.xxxxxxxxx.com/mu/*`加入流量审查白名单，不对这个地址的请求进行审查。

**Comment by mooyxu** [comment]
@zuoruizhi @fsgmhoward 

1、前端没错，网页能正常打开，能进admin查看各种信息。
2、api和pass正确，pass我重新生成了个新的，手动拷贝的，不会出错。
3、CDN没开，万网的域名，去检索看了默认没开。

**Comment by fsgmhoward** [comment]
Em...你是怎么装的ss-panel运行环境，是一键包装的么？有装云锁之类的东西么？

你尝试一下bash执行`curl -A 'Python-urllib/2.7' http://ss.xxxxxxxxxxxxxxx.com/mu/users?key=你的API密匙`，看一下返回内容是什么？

401无非就是两种情况，一是被CDN或者程序防火墙过滤了，二是PASS错了。如果你确定PASS没错的话只能是被过滤了。

**Comment by Pskoty** [comment]
我前端安装的是ss-panel V4，运行时也出现此问题。 V4 的.env 找不到 muKey 选项，这该怎样弄呢？

**Comment by fsgmhoward** [comment]
@Pskoty 请在ss-panel V4的仓库发起issue咨询如何兼容MU V2接口，我无法给你提供帮助。

**Comment by Pskoty** [comment]
@fsgmhoward 感谢你的回复，不过已经在网站控制面板里发现有配置选项，可以设置一些原来.env里面的一些参数，其中就包括muKey.
