### ISSUE TITLE
Deprecate Enforce OTA in Config

### ISSUE THREAD

**Issue by coderfox** [fsgmhoward/shadowsocks-py-mu#41]
As shadowsocks drop OTA suport, I think `SS_OTA` in `config.py` should be dropped.

Furthermore, I think it can be replaced by an option of enforcing AEAD ciphers, or an option of enabling only part of the ciphers available.

**Comment by fsgmhoward** [comment]
OTA is still supported in some versions of SS (such as the original repo `shadowsocks/shadowsocks`). I won't remove it until the original repo removes it.

Enforcing AEAD ciphers can be a new feature. I'll tag this as enhancement.

**Comment by fsgmhoward** [comment]
The feature of enforcement of AEAD ciphers has been implemented and merged to master branch. The removal of OTA will be implemented once upstream (shadowsocks/shadowsocks) does so.
