### ISSUE TITLE
High Memory Demand

### ISSUE THREAD

**Issue by fsgmhoward** [fsgmhoward/shadowsocks-py-mu#42]
There may be a memory leak in the thread as memory usage progressively increases until the program killed by the kernel.

Problem should come from af51e1ca6 and the following commits.

**Comment by fsgmhoward** [comment]
Hotfix: https://github.com/fsgmhoward/shadowsocks-py-mu/commit/841b172f2daa3f0263b9cc35132a5209bbb89473

**Comment by fsgmhoward** [comment]
Update: 841b172 only partially fixed the problem, and memory leak still occur (though not that serious compared to previous version). Further investigation required.

**Comment by coderfox** [comment]
I have found that on several occasions, there is a burst in memory for 6 hours, which may relate to memory leak, while in most times, the memory demand is normal.

**Comment by d4boy** [comment]
hi
has been fixed？

**Comment by d4boy** [comment]
I found  memory leak when using udp(
Someone fixes it

**Comment by fsgmhoward** [comment]
@d4boy Merged
Further test in actual run required.

**Comment by d4boy** [comment]
Tested for a week, no memory leaks
You can now close this issue

**Comment by fsgmhoward** [comment]
Confirmed. No memory leak observed.
