### ISSUE TITLE
内存挤爆了，kernel直接干掉python进程

### ISSUE THREAD

**Issue by jqqjj** [fsgmhoward/shadowsocks-py-mu#46]
这个什么时候修改。我是前几天clone下来的。还是会内存被挤爆。
May 14 14:03:39 s1 kernel: python invoked oom-killer: gfp_mask=0x201da, order=0, oom_adj=0, oom_score_adj=0
May 14 14:03:39 s1 kernel: python cpuset=/ mems_allowed=0
May 14 14:03:39 s1 kernel: Pid: 4321, comm: python Tainted: P           -- ------------    2.6.32-642.1.1.el6.x86_64 #1
May 14 14:03:39 s1 kernel: Call Trace:
May 14 14:03:39 s1 kernel: [<ffffffff81131640>] ? dump_header+0x90/0x1b0
May 14 14:03:39 s1 kernel: [<ffffffff8123c20c>] ? security_real_capable_noaudit+0x3c/0x70
May 14 14:03:39 s1 kernel: [<ffffffff81131ac2>] ? oom_kill_process+0x82/0x2a0
May 14 14:03:39 s1 kernel: [<ffffffff81131a01>] ? select_bad_process+0xe1/0x120
May 14 14:03:39 s1 kernel: [<ffffffff81131f00>] ? out_of_memory+0x220/0x3c0
May 14 14:03:39 s1 kernel: [<ffffffff8113e8dc>] ? __alloc_pages_nodemask+0x93c/0x950
May 14 14:03:39 s1 kernel: [<ffffffff81177b2a>] ? alloc_pages_current+0xaa/0x110
May 14 14:03:39 s1 kernel: [<ffffffff8112ea37>] ? __page_cache_alloc+0x87/0x90
May 14 14:03:39 s1 kernel: [<ffffffff8112e41e>] ? find_get_page+0x1e/0xa0
May 14 14:03:39 s1 kernel: [<ffffffff8112f9d7>] ? filemap_fault+0x1a7/0x500
May 14 14:03:39 s1 kernel: [<ffffffff81159394>] ? __do_fault+0x54/0x530
May 14 14:03:39 s1 kernel: [<ffffffff81159967>] ? handle_pte_fault+0xf7/0xb20
May 14 14:03:39 s1 kernel: [<ffffffff811bca80>] ? mntput_no_expire+0x30/0x110
May 14 14:03:39 s1 kernel: [<ffffffff811bca80>] ? mntput_no_expire+0x30/0x110
May 14 14:03:39 s1 kernel: [<ffffffff8115a629>] ? handle_mm_fault+0x299/0x3d0
May 14 14:03:39 s1 kernel: [<ffffffff811a81bb>] ? putname+0x2b/0x40
May 14 14:03:39 s1 kernel: [<ffffffff81052156>] ? __do_page_fault+0x146/0x500
May 14 14:03:39 s1 kernel: [<ffffffff81299b35>] ? _atomic_dec_and_lock+0x55/0x80
May 14 14:03:39 s1 kernel: [<ffffffff8119f884>] ? cp_new_stat+0xe4/0x100
May 14 14:03:39 s1 kernel: [<ffffffff8154dc8e>] ? do_page_fault+0x3e/0xa0
May 14 14:03:39 s1 kernel: [<ffffffff8154af95>] ? page_fault+0x25/0x30
May 14 14:03:39 s1 kernel: Mem-Info:
May 14 14:03:39 s1 kernel: Node 0 DMA per-cpu:
May 14 14:03:39 s1 kernel: CPU    0: hi:    0, btch:   1 usd:   0
May 14 14:03:39 s1 kernel: Node 0 DMA32 per-cpu:
May 14 14:03:39 s1 kernel: CPU    0: hi:  186, btch:  31 usd:  35
May 14 14:03:39 s1 kernel: active_anon:150102 inactive_anon:48 isolated_anon:0
May 14 14:03:39 s1 kernel: active_file:12 inactive_file:986 isolated_file:0
May 14 14:03:39 s1 kernel: unevictable:0 dirty:2 writeback:0 unstable:0
May 14 14:03:39 s1 kernel: free:10343 slab_reclaimable:1551 slab_unreclaimable:7620
May 14 14:03:39 s1 kernel: mapped:231 shmem:53 pagetables:1431 bounce:0
May 14 14:03:39 s1 kernel: Node 0 DMA free:3728kB min:760kB low:948kB high:1140kB active_anon:11320kB inactive_anon:0kB active_file:4kB inactive_file:284kB unevictable:0kB isolated(anon):0kB isolated(file):0kB present:15368kB mlocked:0kB dirty:0kB writeback:0kB mapped:36kB shmem:0kB slab_reclaimable:0kB slab_unreclaimable:240kB kernel_stack:0kB pagetables:8kB unstable:0kB bounce:0kB writeback_tmp:0kB pages_scanned:0 all_unreclaimable? yes
May 14 14:03:39 s1 kernel: lowmem_reserve[]: 0 741 741 741
May 14 14:03:39 s1 kernel: Node 0 DMA32 free:37644kB min:37708kB low:47132kB high:56560kB active_anon:589088kB inactive_anon:192kB active_file:44kB inactive_file:3660kB unevictable:0kB isolated(anon):0kB isolated(file):0kB present:759376kB mlocked:0kB dirty:8kB writeback:0kB mapped:888kB shmem:212kB slab_reclaimable:6204kB slab_unreclaimable:30240kB kernel_stack:2048kB pagetables:5716kB unstable:0kB bounce:0kB writeback_tmp:0kB pages_scanned:74 all_unreclaimable? yes
May 14 14:03:39 s1 kernel: lowmem_reserve[]: 0 0 0 0
May 14 14:03:39 s1 kernel: Node 0 DMA: 4*4kB 10*8kB 9*16kB 5*32kB 2*64kB 3*128kB 3*256kB 0*512kB 0*1024kB 1*2048kB 0*4096kB = 3728kB
May 14 14:03:39 s1 kernel: Node 0 DMA32: 565*4kB 317*8kB 135*16kB 79*32kB 128*64kB 56*128kB 30*256kB 8*512kB 1*1024kB 0*2048kB 0*4096kB = 37644kB
May 14 14:03:39 s1 kernel: 1056 total pagecache pages
May 14 14:03:39 s1 kernel: 0 pages in swap cache

**Comment by fsgmhoward** [comment]
请关注#42。
暂时没解决这个问题，如果不追求AEAD加密算法请回滚(checkout)前几个tag的commit。如果对AEAD有需求的话请暂时使用supervisor之类的自动重启程序。
