### ISSUE TITLE
  pulling error

### ISSUE THREAD

**Issue by renye616** [fsgmhoward/shadowsocks-py-mu#47]
首先，安装好后端的  shadowsocks-py-mu，api_url   api pass 在config.py中设置无问题，节点1服务器已经通过API 完成pulling  和 push 并且功能正常运行。

节点2 服务器 同样配置好api，可以正常pulling user data 下来。
但是pushing user data的时候报错 500. 
这是什么情况
Jun 02 04:36:54 INFO -----------------------------------------
Jun 02 04:36:54 INFO Multi-User Shadowsocks Server Starting...
Jun 02 04:36:54 INFO Current Server Version: 3.3.0-5-g9504e59

Jun 02 04:36:54 INFO Now using MultiUser API as the user interface
Jun 02 04:36:54 INFO Now starting manager thread...
Jun 02 04:36:59 INFO Now starting user pulling thread...

Jun 02 04:37:04 INFO Now starting user pushing thread...
Jun 02 04:37:06 ERROR Except thrown while pushing user data:HTTP Error 500: Internal Server Error
Jun 02 04:39:08 ERROR Except thrown while pushing user data:HTTP Error 500: Internal Server Error

**Comment by renye616** [comment]
防火墙 双方关闭

**Comment by renye616** [comment]
storage 权限正常

**Comment by zuoruizhi** [comment]
node_id正确吗

**Comment by renye616** [comment]
node ID 是正确的 区分开了

**Comment by fsgmhoward** [comment]
检查ss-panel的服务器日志（比如apache/nginx的日志），看看是哪里有问题。
你发ss服务端的日志大家也没法帮你判断是什么问题啊。

**Comment by renye616** [comment]
2017/05/04 02:59:12 [error] 32749#32749: *335 FastCGI sent in stderr: "PHP message: Slim Application Error:
Type: RuntimeException
Message: App\Controllers\AdminController:sysinfo is not resolvable
File: /var/www/ss-panel/vendor/slim/slim/Slim/CallableResolver.php
Line: 82
Trace: #0 /var/www/ss-panel/vendor/slim/slim/Slim/CallableResolverAwareTrait.php(45): Slim\CallableResolver->resolve('App\\Controllers...')
#1 /var/www/ss-panel/vendor/slim/slim/Slim/Route.php(314): Slim\Routable->resolveCallable('App\\Controllers...')
#2 /var/www/ss-panel/app/Middleware/Admin.php(29): Slim\Route->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response))
#3 [internal function]: App\Middleware\Admin->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\Route))
#4 /var/www/ss-panel/vendor/slim/slim/Slim/DeferredCallable.php(37): call_user_func_array(Object(App\Middleware\Admin), Array)
#5 [internal function]: Slim\DeferredCallable->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\Route))
Message: SQLSTATE[HY000]: General error: 1366 Incorrect integer value: '' for column 'sort' at row 1 (SQL: insert into `ss_node` (`name`, `server`, `method`, `custom_method`, `traffic_rate`, `info`, `type`, `status`, `sort`) values (cal, 104.194.94.25, aes-256-cfb, 0, 1, , 1, , ))
File: /var/www/ss-panel/vendor/illuminate/database/Connection.php
Line: 680
Trace: #0 /var/www/ss-panel/vendor/illuminate/database/Connection.php(636): Illuminate\Database\Connection->runQueryCallback('insert into `ss...', Array, Object(Closure))
#1 /var/www/ss-panel/vendor/illuminate/database/Connection.php(409): Illuminate\Database\Connection->run('insert into `ss...', Array, Object(Closure))
#2 /var/www/ss-panel/vendor/illuminate/database/Connection.php(365): Illuminate\Database\Connection->statement('insert into `ss...', Array)
#3 /var/www/ss-panel/vendor/illuminate/database/Query/Processors/Processor.php(32): Illuminate\Database\Connec" while reading response header from upstream, client: 222.90.134.186, server: 104.194.94.25, request: "POST /admin/node HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.0-fpm.sock:", host: "104.194.94.25", referrer: "http://104.194.94.25/admin/node/create"
2017/05/04 03:01:35 [error] 32749#32749: *350 FastCGI sent in stderr: "PHP message: Slim Application Error:
Type: Illuminate\Database\QueryException
Code: HY000

**Comment by renye616** [comment]
nginx 日志sspanel

**Comment by fsgmhoward** [comment]
老铁，你确定你发的是正确的日志么？
API Push操作的只有`/mu/node/X` 和`/mu/user/X`，你这条日志请求的是`/admin/node`啊.....这不是API出错抛出的异常。
顺带提醒，记得隐藏IP。

**Comment by renye616** [comment]
新手，求教，在api服务端哪查看log？ @fsgmhoward

**Comment by fsgmhoward** [comment]
这个不同服务器都不同的啊......请善用谷歌和百度

**Comment by viRikaRe** [comment]
关于原版ss-panel的“App\Controllers\AdminController:sysinfo is not resolvable”错误：  
你可能用的是ss-panel v3大约3.4.6版左右的某个半吊子commit/release，该commit里`app/routes.php`有一行已被修改为

    $this->get('/sys', 'App\Controllers\AdminController:sysinfo');

但对应的`App\Controllers\AdminController.php`尚未添加`sysinfo()`这个function，导致报错。

解决方法一（适用于只跟release的用户）：  
把最新commit里`App\Controllers\AdminController.php`的最后一段抄到你自己的文件里

    public function sysinfo($request, $response, $args)
    {
        return $this->view()->display('admin/sys.tpl');
    }

解决方法二（适用于跟着commits的用户）：  
更新到最新commit即可。
