### ISSUE TITLE
发现一个问题,当账户被禁用之后

### ISSUE THREAD

**Issue by logtee** [fsgmhoward/shadowsocks-py-mu#50]
当enable字段为0的时候 再去连接服务器
ss会down掉
日志
Sep 03 21:50:33 WARNING U[50395] One time auth fail
Sep 03 21:50:34 WARNING send_command exception: timed out
Sep 03 21:50:34 ERROR db thread except:No JSON object could be decoded
Sep 03 21:50:55 ERROR db thread except:timed out
Sep 03 21:51:06 WARNING send_command exception: timed out
Sep 03 21:51:06 ERROR db thread except:No JSON object could be decoded
Sep 03 21:51:38 WARNING send_command exception: timed out
Sep 03 21:51:38 ERROR db thread except:No JSON object could be decoded
Sep 03 21:52:10 WARNING send_command exception: timed out
Sep 03 21:52:10 ERROR db thread except:No JSON object could be decoded
Sep 03 21:52:42 WARNING send_command exception: timed out
Sep 03 21:52:42 ERROR db thread except:No JSON object could be decoded
Sep 03 21:52:57 ERROR db thread except:timed out
Sep 03 21:53:14 WARNING send_command exception: timed out
Sep 03 21:53:14 ERROR db thread except:No JSON object could be decoded
Sep 03 21:53:46 WARNING send_command exception: timed out
Sep 03 21:53:46 ERROR db thread except:No JSON object could be decoded
Sep 03 21:54:18 WARNING send_command exception: timed out
Sep 03 21:54:18 ERROR db thread except:No JSON object could be decoded
Sep 03 21:54:49 WARNING send_command exception: timed out
Sep 03 21:54:49 ERROR db thread except:No JSON object could be decoded
Sep 03 21:54:59 ERROR db thread except:timed out
Sep 03 21:55:21 WARNING send_command exception: timed out
Sep 03 21:55:21 ERROR db thread except:No JSON object could be decoded
Sep 03 21:55:53 WARNING send_command exception: timed out
Sep 03 21:55:53 ERROR db thread except:No JSON object could be decoded
Sep 03 21:56:25 WARNING send_command exception: timed out
Sep 03 21:56:25 ERROR db thread except:No JSON object could be decoded
Sep 03 21:56:57 WARNING send_command exception: timed out
Sep 03 21:56:57 ERROR db thread except:No JSON object could be decoded
Sep 03 21:57:02 ERROR db thread except:timed out
Sep 03 21:57:29 WARNING send_command exception: timed out
Sep 03 21:57:29 ERROR db thread except:No JSON object could be decoded
Sep 03 21:58:01 WARNING send_command exception: timed out
Sep 03 21:58:01 ERROR db thread except:No JSON object could be decoded
Sep 03 21:58:33 WARNING send_command exception: timed out
Sep 03 21:58:33 ERROR db thread except:No JSON object could be decoded
Sep 03 21:59:04 ERROR db thread except:timed out
Sep 03 21:59:05 WARNING send_command exception: timed out
Sep 03 21:59:05 ERROR db thread except:No JSON object could be decoded
Sep 03 21:59:37 WARNING send_command exception: timed out
Sep 03 21:59:37 ERROR db thread except:No JSON object could be decoded
Sep 03 22:00:09 WARNING send_command exception: timed out
Sep 03 22:00:09 ERROR db thread except:No JSON object could be decoded
Sep 03 22:00:41 WARNING send_command exception: timed out
Sep 03 22:00:41 ERROR db thread except:No JSON object could be decoded
Sep 03 22:01:06 ERROR db thread except:timed out
Sep 03 22:01:13 WARNING send_command exception: timed out
Sep 03 22:01:13 ERROR db thread except:No JSON object could be decoded
Sep 03 22:01:44 WARNING send_command exception: timed out
Sep 03 22:01:44 ERROR db thread except:No JSON object could be decoded
Sep 03 22:02:17 WARNING send_command exception: timed out
Sep 03 22:02:17 ERROR db thread except:No JSON object could be decoded
Sep 03 22:02:49 WARNING send_command exception: timed out
Sep 03 22:02:49 ERROR db thread except:No JSON object could be decoded
Sep 03 22:03:08 ERROR db thread except:timed out
Sep 03 22:03:21 WARNING send_command exception: timed out
Sep 03 22:03:21 ERROR db thread except:No JSON object could be decoded
Sep 03 22:03:53 WARNING send_command exception: timed out
Sep 03 22:03:53 ERROR db thread except:No JSON object could be decoded
Sep 03 22:04:25 WARNING send_command exception: timed out
Sep 03 22:04:25 ERROR db thread except:No JSON object could be decoded
Sep 03 22:04:56 WARNING send_command exception: timed out
Sep 03 22:04:56 ERROR db thread except:No JSON object could be decoded
Sep 03 22:05:10 ERROR db thread except:timed out
Sep 03 22:05:28 WARNING send_command exception: timed out
Sep 03 22:05:28 ERROR db thread except:No JSON object could be decoded
Sep 03 22:06:00 WARNING send_command exception: timed out
Sep 03 22:06:00 ERROR db thread except:No JSON object could be decoded
Sep 03 22:06:32 WARNING send_command exception: timed out
Sep 03 22:06:32 ERROR db thread except:No JSON object could be decoded
Sep 03 22:07:04 WARNING send_command exception: timed out
Sep 03 22:07:04 ERROR db thread except:No JSON object could be decoded
Sep 03 22:07:12 ERROR db thread except:timed out
Sep 03 22:07:36 WARNING send_command exception: timed out
Sep 03 22:07:36 ERROR db thread except:No JSON object could be decoded
Sep 03 22:08:07 WARNING send_command exception: timed out
Sep 03 22:08:07 ERROR db thread except:No JSON object could be decoded
Sep 03 22:08:40 WARNING send_command exception: timed out
Sep 03 22:08:40 ERROR db thread except:No JSON object could be decoded
Sep 03 22:09:11 WARNING send_command exception: timed out
Sep 03 22:09:11 ERROR db thread except:No JSON object could be decoded
Sep 03 22:09:14 ERROR db thread except:timed out
Sep 03 22:09:43 WARNING send_command exception: timed out
Sep 03 22:09:43 ERROR db thread except:No JSON object could be decoded
Sep 03 22:10:15 WARNING send_command exception: timed out
Sep 03 22:10:15 ERROR db thread except:No JSON object could be decoded
Sep 03 22:10:47 WARNING send_command exception: timed out
Sep 03 22:10:47 ERROR db thread except:No JSON object could be decoded
Sep 03 22:11:16 ERROR db thread except:timed out
Sep 03 22:11:19 WARNING send_command exception: timed out
Sep 03 22:11:19 ERROR db thread except:No JSON object could be decoded
Sep 03 22:11:51 WARNING send_command exception: timed out
Sep 03 22:11:51 ERROR db thread except:No JSON object could be decoded
Sep 03 22:12:23 WARNING send_command exception: timed out
Sep 03 22:12:23 ERROR db thread except:No JSON object could be decoded
Sep 03 22:12:55 WARNING send_command exception: timed out
Sep 03 22:12:55 ERROR db thread except:No JSON object could be decoded
Sep 03 22:13:18 ERROR db thread except:timed out
Sep 03 22:13:27 WARNING send_command exception: timed out
Sep 03 22:13:27 ERROR db thread except:No JSON object could be decoded
Sep 03 22:13:59 WARNING send_command exception: timed out
Sep 03 22:13:59 ERROR db thread except:No JSON object could be decoded
Sep 03 22:14:31 WARNING send_command exception: timed out
Sep 03 22:14:31 ERROR db thread except:No JSON object could be decoded
Sep 03 22:15:03 WARNING send_command exception: timed out
Sep 03 22:15:03 ERROR db thread except:No JSON object could be decoded
Sep 03 22:15:20 ERROR db thread except:timed out
Sep 03 22:15:34 WARNING send_command exception: timed out
Sep 03 22:15:34 ERROR db thread except:No JSON object could be decoded
Sep 03 22:16:06 WARNING send_command exception: timed out
Sep 03 22:16:06 ERROR db thread except:No JSON object could be decoded
Sep 03 22:16:38 WARNING send_command exception: timed out
Sep 03 22:16:38 ERROR db thread except:No JSON object could be decoded
Sep 03 22:17:10 WARNING send_command exception: timed out
Sep 03 22:17:10 ERROR db thread except:No JSON object could be decoded
Sep 03 22:17:23 ERROR db thread except:timed out
Sep 03 22:17:42 WARNING send_command exception: timed out
Sep 03 22:17:42 ERROR db thread except:No JSON object could be decoded
Sep 03 22:18:14 WARNING send_command exception: timed out
Sep 03 22:18:14 ERROR db thread except:No JSON object could be decoded
Sep 03 22:18:46 WARNING send_command exception: timed out
Sep 03 22:18:46 ERROR db thread except:No JSON object could be decoded
Sep 03 22:19:18 WARNING send_command exception: timed out
Sep 03 22:19:18 ERROR db thread except:No JSON object could be decoded
Sep 03 22:19:25 ERROR db thread except:timed out
Sep 03 22:19:50 WARNING send_command exception: timed out
Sep 03 22:19:50 ERROR db thread except:No JSON object could be decoded
Sep 03 22:20:22 WARNING send_command exception: timed out
Sep 03 22:20:22 ERROR db thread except:No JSON object could be decoded
Sep 03 22:20:54 WARNING send_command exception: timed out
Sep 03 22:20:54 ERROR db thread except:No JSON object could be decoded
Sep 03 22:21:25 WARNING send_command exception: timed out
Sep 03 22:21:25 ERROR db thread except:No JSON object could be decoded
Sep 03 22:21:27 ERROR db thread except:timed out
Sep 03 22:21:58 WARNING send_command exception: timed out
Sep 03 22:21:58 ERROR db thread except:No JSON object could be decoded
Sep 03 22:22:30 WARNING send_command exception: timed out
Sep 03 22:22:30 ERROR db thread except:No JSON object could be decoded
Sep 03 22:23:01 WARNING send_command exception: timed out
Sep 03 22:23:01 ERROR db thread except:No JSON object could be decoded
Sep 03 22:23:29 ERROR db thread except:timed out
Sep 03 22:23:33 WARNING send_command exception: timed out
Sep 03 22:23:33 ERROR db thread except:No JSON object could be decoded
Sep 03 22:24:05 WARNING send_command exception: timed out
Sep 03 22:24:05 ERROR db thread except:No JSON object could be decoded
Sep 03 22:24:37 WARNING send_command exception: timed out
Sep 03 22:24:37 ERROR db thread except:No JSON object could be decoded
Sep 03 22:25:09 WARNING send_command exception: timed out
Sep 03 22:25:09 ERROR db thread except:No JSON object could be decoded
Sep 03 22:25:31 ERROR db thread except:timed out
Sep 03 22:25:41 WARNING send_command exception: timed out
Sep 03 22:25:41 ERROR db thread except:No JSON object could be decoded
Sep 03 22:26:13 WARNING send_command exception: timed out
Sep 03 22:26:13 ERROR db thread except:No JSON object could be decoded
Sep 03 22:26:45 WARNING send_command exception: timed out
Sep 03 22:26:45 ERROR db thread except:No JSON object could be decoded
Sep 03 22:27:17 WARNING send_command exception: timed out
Sep 03 22:27:17 ERROR db thread except:No JSON object could be decoded
Sep 03 22:27:33 ERROR db thread except:timed out
Sep 03 22:27:49 WARNING send_command exception: timed out
Sep 03 22:27:49 ERROR db thread except:No JSON object could be decoded
Sep 03 22:28:21 WARNING send_command exception: timed out
Sep 03 22:28:21 ERROR db thread except:No JSON object could be decoded
Sep 03 22:28:53 WARNING send_command exception: timed out
Sep 03 22:28:53 ERROR db thread except:No JSON object could be decoded
Sep 03 22:29:24 WARNING send_command exception: timed out
Sep 03 22:29:24 ERROR db thread except:No JSON object could be decoded
Sep 03 22:29:35 ERROR db thread except:timed out
Sep 03 22:29:56 WARNING send_command exception: timed out
Sep 03 22:29:56 ERROR db thread except:No JSON object could be decoded
Sep 03 22:30:28 WARNING send_command exception: timed out
Sep 03 22:30:28 ERROR db thread except:No JSON object could be decoded
Sep 03 22:31:00 WARNING send_command exception: timed out
Sep 03 22:31:00 ERROR db thread except:No JSON object could be decoded
Sep 03 22:31:32 WARNING send_command exception: timed out
Sep 03 22:31:32 ERROR db thread except:No JSON object could be decoded
Sep 03 22:31:37 ERROR db thread except:timed out
Sep 03 22:32:04 WARNING send_command exception: timed out
Sep 03 22:32:04 ERROR db thread except:No JSON object could be decoded
Sep 03 22:32:36 WARNING send_command exception: timed out
Sep 03 22:32:36 ERROR db thread except:No JSON object could be decoded
Sep 03 22:33:08 WARNING send_command exception: timed out
Sep 03 22:33:08 ERROR db thread except:No JSON object could be decoded
Sep 03 22:33:39 WARNING send_command exception: timed out
Sep 03 22:33:39 ERROR db thread except:No JSON object could be decoded
Sep 03 22:33:39 ERROR db thread except:timed out
Sep 03 22:34:11 WARNING send_command exception: timed out
Sep 03 22:34:11 ERROR db thread except:No JSON object could be decoded
Sep 03 22:34:43 WARNING send_command exception: timed out
Sep 03 22:34:43 ERROR db thread except:No JSON object could be decoded
Sep 03 22:35:15 WARNING send_command exception: timed out
Sep 03 22:35:15 ERROR db thread except:No JSON object could be decoded
Sep 03 22:35:41 ERROR db thread except:timed out
Sep 03 22:35:47 WARNING send_command exception: timed out
Sep 03 22:35:47 ERROR db thread except:No JSON object could be decoded
Sep 03 22:36:19 WARNING send_command exception: timed out
Sep 03 22:36:19 ERROR db thread except:No JSON object could be decoded
Sep 03 22:36:51 WARNING send_command exception: timed out
Sep 03 22:36:51 ERROR db thread except:No JSON object could be decoded
Sep 03 22:37:23 WARNING send_command exception: timed out
Sep 03 22:37:23 ERROR db thread except:No JSON object could be decoded
Sep 03 22:37:44 ERROR db thread except:timed out
Sep 03 22:37:55 WARNING send_command exception: timed out
Sep 03 22:37:55 ERROR db thread except:No JSON object could be decoded
Sep 03 22:38:27 WARNING send_command exception: timed out
Sep 03 22:38:27 ERROR db thread except:No JSON object could be decoded
Sep 03 22:38:59 WARNING send_command exception: timed out
Sep 03 22:38:59 ERROR db thread except:No JSON object could be decoded
Sep 03 22:39:31 WARNING send_command exception: timed out
Sep 03 22:39:31 ERROR db thread except:No JSON object could be decoded
Sep 03 22:39:46 ERROR db thread except:timed out
Sep 03 22:40:03 WARNING send_command exception: timed out
Sep 03 22:40:03 ERROR db thread except:No JSON object could be decoded
Sep 03 22:40:34 WARNING send_command exception: timed out
Sep 03 22:40:34 ERROR db thread except:No JSON object could be decoded
Sep 03 22:41:06 WARNING send_command exception: timed out
Sep 03 22:41:06 ERROR db thread except:No JSON object could be decoded
Sep 03 22:41:38 WARNING send_command exception: timed out
Sep 03 22:41:38 ERROR db thread except:No JSON object could be decoded
Sep 03 22:41:48 ERROR db thread except:timed out
Sep 03 22:42:10 WARNING send_command exception: timed out
Sep 03 22:42:10 ERROR db thread except:No JSON object could be decoded
Sep 03 22:42:42 WARNING send_command exception: timed out
Sep 03 22:42:42 ERROR db thread except:No JSON object could be decoded
Sep 03 22:43:14 WARNING send_command exception: timed out
Sep 03 22:43:14 ERROR db thread except:No JSON object could be decoded
Sep 03 22:43:46 WARNING send_command exception: timed out
Sep 03 22:43:46 ERROR db thread except:No JSON object could be decoded
Sep 03 22:43:50 ERROR db thread except:timed out
Sep 03 22:44:18 WARNING send_command exception: timed out
Sep 03 22:44:18 ERROR db thread except:No JSON object could be decoded
Sep 03 22:44:50 WARNING send_command exception: timed out
Sep 03 22:44:50 ERROR db thread except:No JSON object could be decoded
Sep 03 22:45:21 WARNING send_command exception: timed out
Sep 03 22:45:21 ERROR db thread except:No JSON object could be decoded
Sep 03 22:45:52 ERROR db thread except:timed out
Sep 03 22:45:53 WARNING send_command exception: timed out
Sep 03 22:45:53 ERROR db thread except:No JSON object could be decoded
Sep 03 22:46:25 WARNING send_command exception: timed out
Sep 03 22:46:25 ERROR db thread except:No JSON object could be decoded
Sep 03 22:46:57 WARNING send_command exception: timed out
Sep 03 22:46:57 ERROR db thread except:No JSON object could be decoded
Sep 03 22:47:30 WARNING send_command exception: timed out
Sep 03 22:47:30 ERROR db thread except:No JSON object could be decoded
Sep 03 22:47:54 ERROR db thread except:timed out
Sep 03 22:48:01 WARNING send_command exception: timed out
Sep 03 22:48:01 ERROR db thread except:No JSON object could be decoded
Sep 03 22:48:33 WARNING send_command exception: timed out
Sep 03 22:48:33 ERROR db thread except:No JSON object could be decoded
Sep 03 22:49:05 WARNING send_command exception: timed out
Sep 03 22:49:05 ERROR db thread except:No JSON object could be decoded
Sep 03 22:49:37 WARNING send_command exception: timed out
Sep 03 22:49:37 ERROR db thread except:No JSON object could be decoded
Sep 03 22:49:56 ERROR db thread except:timed out
Sep 03 22:50:09 WARNING send_command exception: timed out
Sep 03 22:50:09 ERROR db thread except:No JSON object could be decoded
Sep 03 22:50:41 WARNING send_command exception: timed out
Sep 03 22:50:41 ERROR db thread except:No JSON object could be decoded
Sep 03 22:51:13 WARNING send_command exception: timed out
Sep 03 22:51:13 ERROR db thread except:No JSON object could be decoded
Sep 03 22:51:45 WARNING send_command exception: timed out
Sep 03 22:51:45 ERROR db thread except:No JSON object could be decoded
Sep 03 22:51:58 ERROR db thread except:timed out
Sep 03 22:52:17 WARNING send_command exception: timed out
Sep 03 22:52:17 ERROR db thread except:No JSON object could be decoded
Sep 03 22:52:48 WARNING send_command exception: timed out
Sep 03 22:52:48 ERROR db thread except:No JSON object could be decoded
Sep 03 22:53:20 WARNING send_command exception: timed out
Sep 03 22:53:20 ERROR db thread except:No JSON object could be decoded
Sep 03 22:53:52 WARNING send_command exception: timed out
Sep 03 22:53:52 ERROR db thread except:No JSON object could be decoded
Sep 03 22:54:00 ERROR db thread except:timed out
Sep 03 22:54:24 WARNING send_command exception: timed out
Sep 03 22:54:24 ERROR db thread except:No JSON object could be decoded
Sep 03 22:54:56 WARNING send_command exception: timed out
Sep 03 22:54:56 ERROR db thread except:No JSON object could be decoded
Sep 03 22:55:28 WARNING send_command exception: timed out
Sep 03 22:55:28 ERROR db thread except:No JSON object could be decoded
Sep 03 22:56:00 WARNING send_command exception: timed out
Sep 03 22:56:00 ERROR db thread except:No JSON object could be decoded
Sep 03 22:56:02 ERROR db thread except:timed out
Sep 03 22:56:32 WARNING send_command exception: timed out
Sep 03 22:56:32 ERROR db thread except:No JSON object could be decoded
Sep 03 22:57:04 WARNING send_command exception: timed out
Sep 03 22:57:04 ERROR db thread except:No JSON object could be decoded
Sep 03 22:57:36 WARNING send_command exception: timed out
Sep 03 22:57:36 ERROR db thread except:No JSON object could be decoded
Sep 03 22:58:05 ERROR db thread except:timed out
Sep 03 22:58:07 WARNING send_command exception: timed out
Sep 03 22:58:07 ERROR db thread except:No JSON object could be decoded
Sep 03 22:58:39 WARNING send_command exception: timed out
Sep 03 22:58:39 ERROR db thread except:No JSON object could be decoded
Sep 03 22:59:11 WARNING send_command exception: timed out
Sep 03 22:59:11 ERROR db thread except:No JSON object could be decoded
Sep 03 22:59:43 WARNING send_command exception: timed out
Sep 03 22:59:43 ERROR db thread except:No JSON object could be decoded
Sep 03 23:00:07 ERROR db thread except:timed out
Sep 03 23:00:15 WARNING send_command exception: timed out
Sep 03 23:00:15 ERROR db thread except:No JSON object could be decoded
Sep 03 23:00:47 WARNING send_command exception: timed out
Sep 03 23:00:47 ERROR db thread except:No JSON object could be decoded
Sep 03 23:01:19 WARNING send_command exception: timed out
Sep 03 23:01:19 ERROR db thread except:No JSON object could be decoded
Sep 03 23:01:51 WARNING send_command exception: timed out
Sep 03 23:01:51 ERROR db thread except:No JSON object could be decoded
Sep 03 23:02:09 ERROR db thread except:timed out
Sep 03 23:02:23 WARNING send_command exception: timed out
Sep 03 23:02:23 ERROR db thread except:No JSON object could be decoded
Sep 03 23:02:55 WARNING send_command exception: timed out
Sep 03 23:02:55 ERROR db thread except:No JSON object could be decoded
Sep 03 23:03:27 WARNING send_command exception: timed out

**Comment by logtee** [comment]
此时只能重启进程才能连接,如何解决呢?谢谢啦~

**Comment by logtee** [comment]
重新操作一遍,禁用了账户,却没有相同的情况出现,不知道Sep 03 21:50:33 WARNING U[50395] One time auth fail是如何出现的呢?客户端已经没有OTA的选项了,服务端与客户端都没有开启这个

**Comment by logtee** [comment]
Sep 04 17:21:54 WARNING U[50274] One time auth fail
Sep 04 17:21:54 ERROR U[50274] [Errno 111] Connection refused
Sep 04 17:22:02 WARNING unsupported addrtype 104, maybe wrong password or encryption method
Sep 04 17:22:02 ERROR U[50274] TCP Can not parse header when handling connection from ::ffff:172.31.0.1:50274
Sep 04 17:22:02 WARNING unsupported addrtype 18, maybe wrong password or encryption method
Sep 04 17:22:02 ERROR U[50274] TCP Can not parse header when handling connection from ::ffff:172.31.0.1:50274
Sep 04 17:22:02 WARNING unsupported addrtype 0, maybe wrong password or encryption method
Sep 04 17:22:02 ERROR U[50274] TCP Can not parse header when handling connection from ::ffff:172.31.0.1:50274
Sep 04 17:22:02 WARNING unsupported addrtype 194, maybe wrong password or encryption method
Sep 04 17:22:02 ERROR U[50274] TCP Can not parse header when handling connection from ::ffff:172.31.0.1:50274
Sep 04 17:22:02 WARNING unsupported addrtype 144, maybe wrong password or encryption method
Sep 04 17:22:02 ERROR U[50274] TCP Can not parse header when handling connection from ::ffff:172.31.0.1:50274
Sep 04 17:22:02 WARNING unsupported addrtype 122, maybe wrong password or encryption method
Sep 04 17:22:02 ERROR U[50274] TCP Can not parse header when handling connection from ::ffff:172.31.0.1:50274
Sep 04 17:22:02 WARNING unsupported addrtype 150, maybe wrong password or encryption method
Sep 04 17:22:02 ERROR U[50274] TCP Can not parse header when handling connection from ::ffff:172.31.0.1:50274
Sep 04 17:22:02 WARNING unsupported addrtype 224, maybe wrong password or encryption method
Sep 04 17:22:02 ERROR U[50274] TCP Can not parse header when handling connection from ::ffff:172.31.0.1:50274
Sep 04 17:22:02 WARNING unsupported addrtype 39, maybe wrong password or encryption method
Sep 04 17:22:02 ERROR U[50274] TCP Can not parse header when handling connection from ::ffff:172.31.0.1:50274
Sep 04 17:22:02 WARNING unsupported addrtype 106, maybe wrong password or encryption method
Sep 04 17:22:02 ERROR U[50274] TCP Can not parse header when handling connection from ::ffff:172.31.0.1:50274
Sep 04 17:22:02 WARNING unsupported addrtype 47, maybe wrong password or encryption method
Sep 04 17:22:02 ERROR U[50274] TCP Can not parse header when handling connection from ::ffff:172.31.0.1:50274
Sep 04 17:22:02 WARNING unsupported addrtype 93, maybe wrong password or encryption method
Sep 04 17:22:02 ERROR U[50274] TCP Can not parse header when handling connection from ::ffff:172.31.0.1:50274
Sep 04 17:22:02 WARNING unsupported addrtype 223, maybe wrong password or encryption method
Sep 04 17:22:02 ERROR U[50274] TCP Can not parse header when handling connection from ::ffff:172.31.0.1:50274
Sep 04 17:22:02 WARNING unsupported addrtype 199, maybe wrong password or encryption method
Sep 04 17:22:02 ERROR U[50274] TCP Can not parse header when handling connection from ::ffff:172.31.0.1:50274
Sep 04 17:22:02 WARNING unsupported addrtype 120, maybe wrong password or encryption method
Sep 04 17:22:02 ERROR U[50274] TCP Can not parse header when handling connection from ::ffff:172.31.0.1:50274
Sep 04 17:22:02 WARNING unsupported addrtype 122, maybe wrong password or encryption method
Sep 04 17:22:02 ERROR U[50274] TCP Can not parse header when handling connection from ::ffff:172.31.0.1:50274
Sep 04 17:22:02 INFO U[50274] TCP CONN: RP[62506] A[::ffff:172.31.0.1-->c6c7:a61f:7e53:244d:7acd:2e46:dc51:5ab7]
Sep 04 17:22:02 WARNING U[50274] One time auth header is too short
Sep 04 17:22:02 WARNING unsupported addrtype 21, maybe wrong password or encryption method
Sep 04 17:22:02 ERROR U[50274] TCP Can not parse header when handling connection from ::ffff:172.31.0.1:50274
Sep 04 17:22:02 WARNING unsupported addrtype 229, maybe wrong password or encryption method
Sep 04 17:22:02 ERROR U[50274] TCP Can not parse header when handling connection from ::ffff:172.31.0.1:50274
Sep 04 17:22:02 WARNING header is too short
Sep 04 17:22:02 ERROR U[50274] TCP Can not parse header when handling connection from ::ffff:172.31.0.1:50274
Sep 04 17:22:02 WARNING header is too short
Sep 04 17:22:02 ERROR U[50274] TCP Can not parse header when handling connection from ::ffff:172.31.0.1:50274
Sep 04 17:22:02 WARNING unsupported addrtype 104, maybe wrong password or encryption method
Sep 04 17:22:02 ERROR U[50274] TCP Can not parse header when handling connection from ::ffff:172.31.0.1:50274
Sep 04 17:22:03 WARNING unsupported addrtype 10, maybe wrong password or encryption method
Sep 04 17:22:03 ERROR U[50274] TCP Can not parse header when handling connection from ::ffff:172.31.0.1:50274
Sep 04 17:22:03 WARNING unsupported addrtype 2, maybe wrong password or encryption method
Sep 04 17:22:03 ERROR U[50274] TCP Can not parse header when handling connection from ::ffff:172.31.0.1:50274
Sep 04 17:22:03 WARNING unsupported addrtype 128, maybe wrong password or encryption method
Sep 04 17:22:03 ERROR U[50274] TCP Can not parse header when handling connection from ::ffff:172.31.0.1:50274
Sep 04 17:22:03 WARNING header is too short
Sep 04 17:22:03 ERROR U[50274] TCP Can not parse header when handling connection from ::ffff:172.31.0.1:50274
Sep 04 17:22:03 WARNING unsupported addrtype 189, maybe wrong password or encryption method
Sep 04 17:22:03 ERROR U[50274] TCP Can not parse header when handling connection from ::ffff:172.31.0.1:50274
Sep 04 17:22:03 WARNING unsupported addrtype 61, maybe wrong password or encryption method
Sep 04 17:22:03 ERROR U[50274] TCP Can not parse header when handling connection from ::ffff:172.31.0.1:50274
Sep 04 17:22:03 WARNING unsupported addrtype 106, maybe wrong password or encryption method
Sep 04 17:22:03 ERROR U[50274] TCP Can not parse header when handling connection from ::ffff:172.31.0.1:50274
Sep 04 17:22:03 WARNING unsupported addrtype 183, maybe wrong password or encryption method
Sep 04 17:22:03 ERROR U[50274] TCP Can not parse header when handling connection from ::ffff:172.31.0.1:50274
Sep 04 17:22:03 WARNING unsupported addrtype 205, maybe wrong password or encryption method
Sep 04 17:22:03 ERROR U[50274] TCP Can not parse header when handling connection from ::ffff:172.31.0.1:50274
Sep 04 17:22:04 INFO U[50033] TCP CONN: RP[5228] A[::ffff:172.31.0.1-->mtalk.google.com]
Sep 04 17:22:05 INFO U[50274] TCP CONN: RP[63390] A[::ffff:172.31.0.1-->S⸱֔��,ՠj�㭼%ąl䄄͘ 
Υęݧ 5CvךԞB%|ת0uƋ3Ǹڕ䥪ըq6̚]Ջԙ	Ҟ">Lۂ禈˽ߩ܇ЫԎ󥠞󁒟̥@f@^ߋͪ椨FUj޽ڜፊ[駫mA߬ Eﴸ馁ف63Ä��͝񸀦m��ѭզhø倇qYаƑޣZcaڀ뽔܉˱덂Μr��
Sep 04 17:22:05 WARNING U[50274] One time auth fail
Sep 04 17:22:36 WARNING send_command exception: timed out
Sep 04 17:22:36 ERROR db thread except:No JSON object could be decoded
Sep 04 17:23:08 WARNING send_command exception: timed out
Sep 04 17:23:08 ERROR db thread except:No JSON object could be decoded
Sep 04 17:23:39 WARNING send_command exception: timed out
Sep 04 17:23:39 ERROR db thread except:No JSON object could be decoded
Sep 04 17:23:46 ERROR db thread except:timed out
Sep 04 17:24:11 WARNING send_command exception: timed out
Sep 04 17:24:11 ERROR db thread except:No JSON object could be decoded
Sep 04 17:24:42 WARNING send_command exception: timed out
Sep 04 17:24:42 ERROR db thread except:No JSON object could be decoded
Sep 04 17:25:13 WARNING send_command exception: timed out
Sep 04 17:25:13 ERROR db thread except:No JSON object could be decoded
Sep 04 17:25:45 WARNING send_command exception: timed out
Sep 04 17:25:45 ERROR db thread except:No JSON object could be decoded
Sep 04 17:25:48 ERROR db thread except:timed out
Sep 04 17:26:16 WARNING send_command exception: timed out
Sep 04 17:26:16 ERROR db thread except:No JSON object could be decoded
Sep 04 17:26:48 WARNING send_command exception: timed out
Sep 04 17:26:48 ERROR db thread except:No JSON object could be decoded
Sep 04 17:27:19 WARNING send_command exception: timed out
Sep 04 17:27:19 ERROR db thread except:No JSON object could be decoded
Sep 04 17:27:50 ERROR db thread except:timed out
Sep 04 17:27:51 WARNING send_command exception: timed out
Sep 04 17:27:51 ERROR db thread except:No JSON object could be decoded
Sep 04 17:28:22 WARNING send_command exception: timed out
Sep 04 17:28:22 ERROR db thread except:No JSON object could be decoded
Sep 04 17:28:54 WARNING send_command exception: timed out
Sep 04 17:28:54 ERROR db thread except:No JSON object could be decoded
Sep 04 17:29:25 WARNING send_command exception: timed out
Sep 04 17:29:25 ERROR db thread except:No JSON object could be decoded
Sep 04 17:29:53 ERROR db thread except:timed out
Sep 04 17:29:56 WARNING send_command exception: timed out
Sep 04 17:29:56 ERROR db thread except:No JSON object could be decoded
Sep 04 17:30:28 WARNING send_command exception: timed out
Sep 04 17:30:28 ERROR db thread except:No JSON object could be decoded
Sep 04 17:30:59 WARNING send_command exception: timed out
Sep 04 17:30:59 ERROR db thread except:No JSON object could be decoded
Sep 04 17:31:31 WARNING send_command exception: timed out
Sep 04 17:31:31 ERROR db thread except:No JSON object could be decoded
Sep 04 17:31:55 ERROR db thread except:timed out
Sep 04 17:32:02 WARNING send_command exception: timed out
Sep 04 17:32:02 ERROR db thread except:No JSON object could be decoded
Sep 04 17:32:34 WARNING send_command exception: timed out
Sep 04 17:32:34 ERROR db thread except:No JSON object could be decoded
Sep 04 17:33:05 WARNING send_command exception: timed out
Sep 04 17:33:05 ERROR db thread except:No JSON object could be decoded
Sep 04 17:33:37 WARNING send_command exception: timed out
Sep 04 17:33:37 ERROR db thread except:No JSON object could be decoded
Sep 04 17:33:57 ERROR db thread except:timed out
Sep 04 17:34:08 WARNING send_command exception: timed out

**Comment by fsgmhoward** [comment]
没有必要把重复的log发这么多行，这样做只会导致想帮你的人心烦。

还有就是发issue之前先看看/搜索以往的issue，请参照#36。
