### ISSUE TITLE
为什么日志里面不显示来源IP呢

### ISSUE THREAD

**Issue by logtee** [fsgmhoward/shadowsocks-py-mu#51]
使用的是最新的版本3.1.1
log
Sep 05 16:26:57 WARNING unsupported addrtype 251, maybe wrong password or encryption method
Sep 05 16:26:57 ERROR U[50078] TCP Can not parse header when handling connection from ::ffff:172.21.43.232:50078
这个IP应该是来源IP吧,但是实际上是eth0的IP,这是什么问题呢?

**Comment by fsgmhoward** [comment]
这个BUG我无法重现。
会不会是你本机有个程序在访问你的50078端口？你可以使用`lsof -i:50078`查看当前50078端口所有的TCP连接与其源地址（如果是本机发起的话可以看到源程序）

**Comment by logtee** [comment]
root@iZt4nb:~# lsof -i:50078
COMMAND  PID USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
python  2378 root  137u  IPv6 320321      0t0  TCP *:50078 (LISTEN)
python  2378 root  138u  IPv6 320322      0t0  UDP *:50078
python  2378 root  285u  IPv6 467748      0t0  TCP 172.21.43.232:50078->36.5.149.44:50854 (ESTABLISHED)
python  2378 root  335u  IPv6 467750      0t0  TCP 172.21.43.232:50078->36.5.149.44:50855 (ESTABLISHED)
并没有其他的程序访问50078端口呢
root      2378  0.1  1.9 271468 19288 ?        Sl   16:22   0:41 python /root/shadowsocks-py-mu/shadowsocks/servers.py

**Comment by logtee** [comment]
另外我检查一下别的服务器,也都是这么显示的
Sep 05 23:19:49 INFO U[50219] TCP CONN: RP[443] A[::ffff:220.130.74.231-->secclientgw.alipay.com]
按照说明::ffff:220.130.74.231应该是client的ip才对吧?可是变成了服务器的IP,难道是配置的问题吗?我看了下选项,是不是和SS_BIND_IP的值有关呢?我是这样设置的SS_BIND_IP = '::',莫非应该用0.0.0.0

**Comment by logtee** [comment]
改成SS_BIND_IP = '0.0.0.0'之后,显示的还是服务器的IP
Sep 05 23:30:45 WARNING unsupported addrtype 135, maybe wrong password or encryption method
Sep 05 23:30:45 ERROR U[50078] TCP Can not parse header when handling connection from 172.21.43.232:50078

**Comment by fsgmhoward** [comment]
对，这个显示的确实应该是ClientIP才对，问题是我没法重现你这个问题，你用的是主分支还是开发分支/什么系统/什么版本的python？

**Comment by logtee** [comment]
使用的是 releases 3.1.1
系统:debian 8
python版本 2.7.9
配置文件:http://d.pr/f/mT3Wgv

**Comment by logtee** [comment]
我新开了一台服务器,也算是同样的问题
Sep 06 00:38:08 INFO U[50006] TCP CONN: RP[443] A[45.32.27.41-->r1---sn-oguesnz6.googlevideo.com]
Sep 06 00:38:22 INFO U[50006] TCP CONN: RP[443] A[45.32.27.41-->bolt.dropbox.com]
为什么没法子重现呢?要不我把服务器信息发邮件给您,您帮我看看?

**Comment by fsgmhoward** [comment]
你使用最新版本试试（不要看release直接git clone master分支）。你这个问题我从来没碰上过，以前也从没人提出过（我自己过很多台机子都没出现这情况）...

3.1.1实际上不是最新版（看发布日期），因为我很久没发布过新版本。请尝试最新版本看是否还有这个问题

**Comment by logtee** [comment]
git clone 之后问题解决了,谢谢~
