### ISSUE TITLE
现在的版本支持AEAD吗

### ISSUE THREAD

**Issue by logtee** [fsgmhoward/shadowsocks-py-mu#56]
看了下commits似乎是支持的
可是我在数据库你把加密方式改成aes-256-gcm,进程就崩溃了,然后死循环了
Oct 10 04:47:19 ERROR Finalize cipher failed
Oct 10 04:47:20 INFO -----------------------------------------
Oct 10 04:47:20 INFO Multi-User Shadowsocks Server Starting...
Oct 10 04:47:20 INFO Current Server Version: 3.3.0
Oct 10 04:47:20 INFO Now using MySQL Database as the user interface
Oct 10 04:47:20 INFO Now starting manager thread...
Oct 10 04:47:25 INFO Now starting user pulling thread...

**Comment by fsgmhoward** [comment]
这是最新版本么？

无法重现你的问题，AEAD是支持的并且我的服务器长时间运行并没有发现什么问题（多个端口使用AEAD加密）。

**Comment by logtee** [comment]
应该是上个版本的3.3.0

**Comment by fsgmhoward** [comment]
请使用3.4.0重试（建议使用git clone）

**Comment by fsgmhoward** [comment]
请使用3.4.0重试（建议使用git clone）

**Comment by logtee** [comment]
我看到最新的release3.4.0这么说:There may be unidentified bugs because merged upstream is not a release for production
3.4.0可以愉快的玩耍吗?

**Comment by logtee** [comment]
git clone 最新版之后好像正常了
