### ISSUE TITLE
No JSON object could be decoded 

### ISSUE THREAD

**Issue by 92Yu** [fsgmhoward/shadowsocks-py-mu#58]
ss-panel v3版本，报错如下：
`
Nov 29 03:22:55 INFO -----------------------------------------
Nov 29 03:22:55 INFO Multi-User Shadowsocks Server Starting...
Nov 29 03:22:55 INFO Current Server Version: 3.4.0-1-gf571a08

Nov 29 03:22:55 INFO Now using MultiUser API as the user interface
Nov 29 03:22:55 INFO Now starting manager thread...
Nov 29 03:23:00 INFO Now starting user pulling thread...
Nov 29 03:23:00 ERROR Except thrown while pulling user data:No JSON object could be decoded
Nov 29 03:23:05 INFO Now starting user pushing thread...
Nov 29 03:23:05 ERROR Except thrown while pushing user data:No JSON object could be decoded
`
我的API_URL使用的ip，我没接触过网站这块，请问这个有什么解决办法吗？

**Comment by fsgmhoward** [comment]
请先搜索已经关闭的Issue再开新的。请参照#24与#53。

**Comment by 92Yu** [comment]
e 我看了之前的issue，因为情况有些不一样，而我知识有限，理解有偏差，所以才开新的，多有打扰，还请谅解。

**Comment by fsgmhoward** [comment]
那你倒是描述一下你的情况啊.........你就发个`No JSON object could be decoded`谁能看出这是什么原因。

贴配置文件、curl结果（[看这里](https://github.com/fsgmhoward/shadowsocks-py-mu/issues/24#issuecomment-250981376)）

顺带一提，新版本的ss-panel的链接应该长这个样：http://<你的域名>/mu/v2

**Comment by 92Yu** [comment]
配置如下：
“””
CONFIG_VERSION = '20160623-2'


# Manyuser Interface Settings
# ---------------------------
# If API is enabled, database will be no longer used
# The known app that supports API is SS-Panel V3
# Be careful and check whether your app supports this API BEFORE you enable this feature
API_ENABLED = True

# Database Config
MYSQL_HOST = 'mengsky.net'
MYSQL_PORT = 3306
MYSQL_USER = 'root'
MYSQL_PASS = 'root'
MYSQL_DB = 'shadowsocks'
# USUALLY this variable do not need to be changed
MYSQL_USER_TABLE = 'user'
# This is also the timeout of connecting to the API
MYSQL_TIMEOUT = 30

# Shadowsocks MultiUser API Settings
API_URL = 'http://xxxxx(我的ip)xxx/mu/v2'
# API Key (you can find this in the .env file if you are using SS-Panel V3)
API_PASS = 'xxxx'
NODE_ID = '1'

# Time interval between 2 pulls from the database or API
CHECKTIME = 30
# Time interval between 2 pushes to the database or API
SYNCTIME = 120
# Choose True if you want to use custom method and False if you don't
CUSTOM_METHOD = True


# Manager Settings
# ----------------
# USUALLY you can just keep this section unchanged
# It is not necessary to change the password if you only listen on 127.0.0.1
MANAGE_PASS = 'passwd'
# if you want manage in other server you should set this value to global ip
MANAGE_BIND_IP = '127.0.0.1'
# make sure this port is idle
MANAGE_PORT = 65000


# Network Settings
# ----------------
# Address binding settings
# if you want to bind ipv4 and ipv6 please use '::'
# if you want to bind only all of ipv4 please use '0.0.0.0'
# if you want to bind a specific IP you may use something like '4.4.4.4'
SS_BIND_IP = '::'
# This default method will be replaced by database record if applicable
SS_METHOD = 'aes-256-cfb'
# Choose whether enforce Shadowsocks One Time Auth (OTA)
# OTA will still be enabled for the client if it sends an AUTH Address type(0x10)
SS_OTA = False
# Skip listening these ports
SS_SKIP_PORTS = [80]
# TCP Fastopen (Some OS may not support this, Eg.: Windows)
SS_FASTOPEN = False
# Shadowsocks Time Out
# It should > 180s as some protocol has keep-alive packet of 3 min, Eg.: bt
SS_TIMEOUT = 185


# Firewall Settings
# -----------------
# These settings are to prevent user from abusing your service
SS_FIREWALL_ENABLED = True
# Mode = whitelist or blacklist
SS_FIREWALL_MODE = 'blacklist'
# Member ports should be INTEGERS
# Only Ban these target ports (for blacklist mode)
SS_BAN_PORTS = [22, 23, 25]
# Only Allow these target ports (for whitelist mode)
SS_ALLOW_PORTS = [53, 80, 443, 8080, 8081]
# Trusted users (all target ports will be not be blocked for these users)
SS_FIREWALL_TRUSTED = [443]
# Banned Target IP List
SS_FORBIDDEN_IP = []


# Logging and Debugging Settings
# --------------------------
LOG_ENABLE = True
SS_VERBOSE = False
# Available Log Level: logging.NOTSET|DEBUG|INFO|WARNING|ERROR|CRITICAL
LOG_LEVEL = logging.INFO
LOG_FILE = 'shadowsocks.log'
# The following format is the one suggested for debugging
# LOG_FORMAT = '%(asctime)s %(filename)s[line:%(lineno)d] %(levelname)s %(message)s'
LOG_FORMAT = '%(asctime)s %(levelname)s %(message)s'
LOG_DATE_FORMAT = '%b %d %H:%M:%S'
“”“
curl 请求如下：
“””
<html><head><meta http-equiv='Content-Type' content='text/html; charset=utf-8'><title>Slim Application Error</title><style>body{margin:0;padding:30px;font:12px/1.5 Helvetica,Arial,Verdana,sans-serif;}h1{margin:0;font-size:48px;font-weight:normal;line-height:48px;}strong{display:inline-block;width:65px;}</style></head><body><h1>Slim Application Error</h1><p>A website error has occurred. Sorry for the temporary inconvenience.</p></body></html>
“””
API_URL我试了带v2和不带v2的，结果都一样，感谢

**Comment by 92Yu** [comment]
配置如下：
>
CONFIG_VERSION = '20160623-2'

#Manyuser Interface Settings
#---------------------------
#If API is enabled, database will be no longer used
#The known app that supports API is SS-Panel V3
#Be careful and check whether your app supports this API BEFORE you enable this feature
API_ENABLED = True

#Database Config
MYSQL_HOST = 'mengsky.net'
MYSQL_PORT = 3306
MYSQL_USER = 'root'
MYSQL_PASS = 'root'
MYSQL_DB = 'shadowsocks'
#USUALLY this variable do not need to be changed
MYSQL_USER_TABLE = 'user'
#This is also the timeout of connecting to the API
MYSQL_TIMEOUT = 30

#Shadowsocks MultiUser API Settings
API_URL = 'http://xxxxx(我的ip)xxx/mu/v2'
#API Key (you can find this in the .env file if you are using SS-Panel V3)
API_PASS = 'xxxx'
NODE_ID = '1'

#Time interval between 2 pulls from the database or API
CHECKTIME = 30
#Time interval between 2 pushes to the database or API
SYNCTIME = 120
#Choose True if you want to use custom method and False if you don't
CUSTOM_METHOD = True

#Manager Settings
#----------------
#USUALLY you can just keep this section unchanged
#It is not necessary to change the password if you only listen on 127.0.0.1
MANAGE_PASS = 'passwd'
#if you want manage in other server you should set this value to global ip
MANAGE_BIND_IP = '127.0.0.1'
#make sure this port is idle
MANAGE_PORT = 65000

#Network Settings
#----------------
#Address binding settings
#if you want to bind ipv4 and ipv6 please use '::'
#if you want to bind only all of ipv4 please use '0.0.0.0'
#if you want to bind a specific IP you may use something like '4.4.4.4'
SS_BIND_IP = '::'
#This default method will be replaced by database record if applicable
SS_METHOD = 'aes-256-cfb'
#Choose whether enforce Shadowsocks One Time Auth (OTA)
#OTA will still be enabled for the client if it sends an AUTH Address type(0x10)
SS_OTA = False
#Skip listening these ports
SS_SKIP_PORTS = [80]
#TCP Fastopen (Some OS may not support this, Eg.: Windows)
SS_FASTOPEN = False
#Shadowsocks Time Out
#It should > 180s as some protocol has keep-alive packet of 3 min, Eg.: bt
SS_TIMEOUT = 185

#Firewall Settings
#-----------------
#These settings are to prevent user from abusing your service
SS_FIREWALL_ENABLED = True
#Mode = whitelist or blacklist
SS_FIREWALL_MODE = 'blacklist'
#Member ports should be INTEGERS
#Only Ban these target ports (for blacklist mode)
SS_BAN_PORTS = [22, 23, 25]
#Only Allow these target ports (for whitelist mode)
SS_ALLOW_PORTS = [53, 80, 443, 8080, 8081]
#Trusted users (all target ports will be not be blocked for these users)
SS_FIREWALL_TRUSTED = [443]
#Banned Target IP List
SS_FORBIDDEN_IP = []

#Logging and Debugging Settings
#--------------------------
LOG_ENABLE = True
SS_VERBOSE = False
#Available Log Level: logging.NOTSET|DEBUG|INFO|WARNING|ERROR|CRITICAL
LOG_LEVEL = logging.INFO
LOG_FILE = 'shadowsocks.log'
#The following format is the one suggested for debugging
#LOG_FORMAT = '%(asctime)s %(filename)s[line:%(lineno)d] %(levelname)s %(message)s'
LOG_FORMAT = '%(asctime)s %(levelname)s %(message)s'
LOG_DATE_FORMAT = '%b %d %H:%M:%S'

curl 请求结果如下：
’<html><head><meta http-equiv='Content-Type' content='text/html; charset=utf-8'><title>Slim Application Error</title><style>body{margin:0;padding:30px;font:12px/1.5 Helvetica,Arial,Verdana,sans-serif;}h1{margin:0;font-size:48px;font-weight:normal;line-height:48px;}strong{display:inline-block;width:65px;}</style></head><body><h1>Slim Application Error</h1><p>A website error has occurred. Sorry for the temporary inconvenience.</p></body></html>’

API_URL我试了带v2和不带v2的，结果都一样，感谢

**Comment by fsgmhoward** [comment]
看curl结果的话这是ss-panel的错误。请去ss-panel的代码仓库处开一个issue问解决方案。此仓库的issue只用于讨论ss-py-mu的问题。

你ss-py-mu的配置貌似并没有什么问题。
