### ISSUE TITLE
是否支持simple-obfs

### ISSUE THREAD

**Issue by Ahaochan** [fsgmhoward/shadowsocks-py-mu#65]
请问现在支持[simple-obfs](https://github.com/shadowsocks/simple-obfs)进行多用户混淆吗？
单用户可以外面套个obfs，多用户不知道怎么处理。

**Comment by fsgmhoward** [comment]
@Ahaochan 多用户的话应该需要每个端口各套一个obfs，应该没有官方支持的多用户解决方案（据我所知）。

**Comment by bazingaterry** [comment]
可以用 shadowsocks-libev 的 ss-manager

**Comment by Ahaochan** [comment]
好的感谢两位大佬，我去研究下
